services:
  lastgram-bot:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      # keys are DATABASE_URL, FM_API_KEY, FM_API_SECRET, DITTO_URL, DITTO_API_KEY, TELEGRAM_TOKEN, GENIUS_SECRET_KEY, DISCORD_TOKEN, DROP_PENDING_UPDATES_ON_START, DISCORD_CLIENT_ID, #DISCORD_UPDATE_COMMANDS_ON_START, DEBUGGING'
      - DATABASE_URL=postgres://lg:lgnextrocks@lastgram-database:5432/lastgram
      - CASSANDRA_HOST=lastgram-scylla
      - REDIS_URL=redis://lastgram-redis:6379
      - FM_API_KEY=${project.FM_API_KEY}
      - FM_API_SECRET=${project.FM_API_SECRET}
      - DITTO_URL=${environment.DITTO_URL}
      - DITTO_API_KEY=${project.DITTO_API_KEY}
      - TELEGRAM_TOKEN=${environment.TELEGRAM_TOKEN}
      - GENIUS_SECRET_KEY=${project.GENIUS_SECRET_KEY}
      - DISCORD_TOKEN=${environment.DISCORD_TOKEN}
      - DROP_PENDING_UPDATES_ON_START=${environment.DROP_PENDING_UPDATES_ON_START}
      - DISCORD_CLIENT_ID=${environment.DISCORD_CLIENT_ID}
      - DISCORD_UPDATE_COMMANDS_ON_START=${environment.DISCORD_UPDATE_COMMANDS_ON_START}
      - DEBUGGING=${environment.DEBUGGING}
    depends_on:
      - lastgram-database
      - lastgram-redis
      - lastgram-scylla

  lastgram-database:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: lastgram
      POSTGRES_USER: lg
      POSTGRES_PASSWORD: lgnextrocks
    volumes:
      - pg-lg:/var/lib/postgresql/data

  lastgram-redis:
    image: valkey/valkey
    restart: unless-stopped
    volumes:
      - redis-lg:/data
    ports:
      - '127.0.0.1:6379:6379'

  lastgram-scylla:
    image: scylladb/scylla
    restart: unless-stopped
    ports:
      - '127.0.0.1:9042:9042'
    volumes:
      - scylla-lg:/var/lib/scylla

volumes:
    pg-lg:
    redis-lg:
    scylla-lg: