/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file should be your main import to use Prisma-related types and utilities in a browser. 
 * Use it to get access to models, enums, and input types.
 * 
 * This file does not contain a `PrismaClient` class, nor several other helpers that are intended as server-side only.
 * See `client.ts` for the standard, server-side entry point.
 *
 * 🟢 You can import this file directly.
 */

import * as Prisma from './internal/prismaNamespaceBrowser'

export { Prisma }
export * as $Enums from './enums'
export * from './enums'
/**
 * Model User
 *
 */
export type User = Prisma.UserModel
/**
 * Model FmDisplayName
 *
 */
export type FmDisplayName = Prisma.FmDisplayNameModel
/**
 * Model Artist
 *
 */
export type Artist = Prisma.ArtistModel
/**
 * Model ArtistScrobble
 *
 */
export type ArtistScrobble = Prisma.ArtistScrobbleModel
/**
 * Model GroupMember
 *
 */
export type GroupMember = Prisma.GroupMemberModel
/**
 * Model Crown
 *
 */
export type Crown = Prisma.CrownModel
/**
 * Model CrownHolder
 *
 */
export type CrownHolder = Prisma.CrownHolderModel
