
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
* This file exports all enum related types from the schema.
*
* 🟢 You can import this file directly.
*/

export const EntityType = {
  ARTIST: 'ARTIST',
  ALBUM: 'ALBUM',
  TRACK: 'TRACK'
} as const

export type EntityType = (typeof EntityType)[keyof typeof EntityType]
