/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck
/*
 * This file exports the `CrownHolder` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model CrownHolder
 *
 */
export type CrownHolderModel = runtime.Types.Result.DefaultSelection<Prisma.$CrownHolderPayload>

export type AggregateCrownHolder = {
    _count: CrownHolderCountAggregateOutputType | null
    _avg: CrownHolderAvgAggregateOutputType | null
    _sum: CrownHolderSumAggregateOutputType | null
    _min: CrownHolderMinAggregateOutputType | null
    _max: CrownHolderMaxAggregateOutputType | null
}

export type CrownHolderAvgAggregateOutputType = {
    id: number | null
    playCount: number | null
}

export type CrownHolderSumAggregateOutputType = {
    id: number | null
    playCount: number | null
}

export type CrownHolderMinAggregateOutputType = {
    id: number | null
    groupId: string | null
    artistId: string | null
    fmUsername: string | null
    playCount: number | null
    createdAt: Date | null
}

export type CrownHolderMaxAggregateOutputType = {
    id: number | null
    groupId: string | null
    artistId: string | null
    fmUsername: string | null
    playCount: number | null
    createdAt: Date | null
}

export type CrownHolderCountAggregateOutputType = {
    id: number
    groupId: number
    artistId: number
    fmUsername: number
    playCount: number
    createdAt: number
    _all: number
}


export type CrownHolderAvgAggregateInputType = {
    id?: true
    playCount?: true
}

export type CrownHolderSumAggregateInputType = {
    id?: true
    playCount?: true
}

export type CrownHolderMinAggregateInputType = {
    id?: true
    groupId?: true
    artistId?: true
    fmUsername?: true
    playCount?: true
    createdAt?: true
}

export type CrownHolderMaxAggregateInputType = {
    id?: true
    groupId?: true
    artistId?: true
    fmUsername?: true
    playCount?: true
    createdAt?: true
}

export type CrownHolderCountAggregateInputType = {
    id?: true
    groupId?: true
    artistId?: true
    fmUsername?: true
    playCount?: true
    createdAt?: true
    _all?: true
}

export type CrownHolderAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
    /**
     * Filter which CrownHolder to aggregate.
     */
    where?: Prisma.CrownHolderWhereInput
    /**
     * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
     *
     * Determine the order of CrownHolders to fetch.
     */
    orderBy?: Prisma.CrownHolderOrderByWithRelationInput | Prisma.CrownHolderOrderByWithRelationInput[]
    /**
     * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
     *
     * Sets the start position
     */
    cursor?: Prisma.CrownHolderWhereUniqueInput
    /**
     * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
     *
     * Take `±n` CrownHolders from the position of the cursor.
     */
    take?: number
    /**
     * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
     *
     * Skip the first `n` CrownHolders.
     */
    skip?: number
    /**
     * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
     *
     * Count returned CrownHolders
     **/
    _count?: true | CrownHolderCountAggregateInputType
    /**
     * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
     *
     * Select which fields to average
     **/
    _avg?: CrownHolderAvgAggregateInputType
    /**
     * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
     *
     * Select which fields to sum
     **/
    _sum?: CrownHolderSumAggregateInputType
    /**
     * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
     *
     * Select which fields to find the minimum value
     **/
    _min?: CrownHolderMinAggregateInputType
    /**
     * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
     *
     * Select which fields to find the maximum value
     **/
    _max?: CrownHolderMaxAggregateInputType
}

export type GetCrownHolderAggregateType<T extends CrownHolderAggregateArgs> = {
    [P in keyof T & keyof AggregateCrownHolder]: P extends '_count' | 'count'
        ? T[P] extends true
            ? number
            : Prisma.GetScalarType<T[P], AggregateCrownHolder[P]>
        : Prisma.GetScalarType<T[P], AggregateCrownHolder[P]>
}


export type CrownHolderGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
    where?: Prisma.CrownHolderWhereInput
    orderBy?: Prisma.CrownHolderOrderByWithAggregationInput | Prisma.CrownHolderOrderByWithAggregationInput[]
    by: Prisma.CrownHolderScalarFieldEnum[] | Prisma.CrownHolderScalarFieldEnum
    having?: Prisma.CrownHolderScalarWhereWithAggregatesInput
    take?: number
    skip?: number
    _count?: CrownHolderCountAggregateInputType | true
    _avg?: CrownHolderAvgAggregateInputType
    _sum?: CrownHolderSumAggregateInputType
    _min?: CrownHolderMinAggregateInputType
    _max?: CrownHolderMaxAggregateInputType
}

export type CrownHolderGroupByOutputType = {
    id: number
    groupId: string
    artistId: string
    fmUsername: string
    playCount: number
    createdAt: Date
    _count: CrownHolderCountAggregateOutputType | null
    _avg: CrownHolderAvgAggregateOutputType | null
    _sum: CrownHolderSumAggregateOutputType | null
    _min: CrownHolderMinAggregateOutputType | null
    _max: CrownHolderMaxAggregateOutputType | null
}

type GetCrownHolderGroupByPayload<T extends CrownHolderGroupByArgs> = Prisma.PrismaPromise<
    Array<
        Prisma.PickEnumerable<CrownHolderGroupByOutputType, T['by']> &
        {
            [P in ((keyof T) & (keyof CrownHolderGroupByOutputType))]: P extends '_count'
            ? T[P] extends boolean
                ? number
                : Prisma.GetScalarType<T[P], CrownHolderGroupByOutputType[P]>
            : Prisma.GetScalarType<T[P], CrownHolderGroupByOutputType[P]>
        }
    >
>


export type CrownHolderWhereInput = {
    AND?: Prisma.CrownHolderWhereInput | Prisma.CrownHolderWhereInput[]
    OR?: Prisma.CrownHolderWhereInput[]
    NOT?: Prisma.CrownHolderWhereInput | Prisma.CrownHolderWhereInput[]
    id?: Prisma.IntFilter<"CrownHolder"> | number
    groupId?: Prisma.StringFilter<"CrownHolder"> | string
    artistId?: Prisma.StringFilter<"CrownHolder"> | string
    fmUsername?: Prisma.StringFilter<"CrownHolder"> | string
    playCount?: Prisma.IntFilter<"CrownHolder"> | number
    createdAt?: Prisma.DateTimeFilter<"CrownHolder"> | Date | string
    artist?: Prisma.XOR<Prisma.ArtistScalarRelationFilter, Prisma.ArtistWhereInput>
}

export type CrownHolderOrderByWithRelationInput = {
    id?: Prisma.SortOrder
    groupId?: Prisma.SortOrder
    artistId?: Prisma.SortOrder
    fmUsername?: Prisma.SortOrder
    playCount?: Prisma.SortOrder
    createdAt?: Prisma.SortOrder
    artist?: Prisma.ArtistOrderByWithRelationInput
}

export type CrownHolderWhereUniqueInput = Prisma.AtLeast<{
    id?: number
    groupId_artistId_fmUsername?: Prisma.CrownHolderGroupIdArtistIdFmUsernameCompoundUniqueInput
    AND?: Prisma.CrownHolderWhereInput | Prisma.CrownHolderWhereInput[]
    OR?: Prisma.CrownHolderWhereInput[]
    NOT?: Prisma.CrownHolderWhereInput | Prisma.CrownHolderWhereInput[]
    groupId?: Prisma.StringFilter<"CrownHolder"> | string
    artistId?: Prisma.StringFilter<"CrownHolder"> | string
    fmUsername?: Prisma.StringFilter<"CrownHolder"> | string
    playCount?: Prisma.IntFilter<"CrownHolder"> | number
    createdAt?: Prisma.DateTimeFilter<"CrownHolder"> | Date | string
    artist?: Prisma.XOR<Prisma.ArtistScalarRelationFilter, Prisma.ArtistWhereInput>
}, "id" | "groupId_artistId_fmUsername">

export type CrownHolderOrderByWithAggregationInput = {
    id?: Prisma.SortOrder
    groupId?: Prisma.SortOrder
    artistId?: Prisma.SortOrder
    fmUsername?: Prisma.SortOrder
    playCount?: Prisma.SortOrder
    createdAt?: Prisma.SortOrder
    _count?: Prisma.CrownHolderCountOrderByAggregateInput
    _avg?: Prisma.CrownHolderAvgOrderByAggregateInput
    _max?: Prisma.CrownHolderMaxOrderByAggregateInput
    _min?: Prisma.CrownHolderMinOrderByAggregateInput
    _sum?: Prisma.CrownHolderSumOrderByAggregateInput
}

export type CrownHolderScalarWhereWithAggregatesInput = {
    AND?: Prisma.CrownHolderScalarWhereWithAggregatesInput | Prisma.CrownHolderScalarWhereWithAggregatesInput[]
    OR?: Prisma.CrownHolderScalarWhereWithAggregatesInput[]
    NOT?: Prisma.CrownHolderScalarWhereWithAggregatesInput | Prisma.CrownHolderScalarWhereWithAggregatesInput[]
    id?: Prisma.IntWithAggregatesFilter<"CrownHolder"> | number
    groupId?: Prisma.StringWithAggregatesFilter<"CrownHolder"> | string
    artistId?: Prisma.StringWithAggregatesFilter<"CrownHolder"> | string
    fmUsername?: Prisma.StringWithAggregatesFilter<"CrownHolder"> | string
    playCount?: Prisma.IntWithAggregatesFilter<"CrownHolder"> | number
    createdAt?: Prisma.DateTimeWithAggregatesFilter<"CrownHolder"> | Date | string
}

export type CrownHolderCreateInput = {
    groupId: string
    fmUsername: string
    playCount: number
    createdAt?: Date | string
    artist: Prisma.ArtistCreateNestedOneWithoutCrownHoldersInput
}

export type CrownHolderUncheckedCreateInput = {
    id?: number
    groupId: string
    artistId: string
    fmUsername: string
    playCount: number
    createdAt?: Date | string
}

export type CrownHolderUpdateInput = {
    groupId?: Prisma.StringFieldUpdateOperationsInput | string
    fmUsername?: Prisma.StringFieldUpdateOperationsInput | string
    playCount?: Prisma.IntFieldUpdateOperationsInput | number
    createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
    artist?: Prisma.ArtistUpdateOneRequiredWithoutCrownHoldersNestedInput
}

export type CrownHolderUncheckedUpdateInput = {
    id?: Prisma.IntFieldUpdateOperationsInput | number
    groupId?: Prisma.StringFieldUpdateOperationsInput | string
    artistId?: Prisma.StringFieldUpdateOperationsInput | string
    fmUsername?: Prisma.StringFieldUpdateOperationsInput | string
    playCount?: Prisma.IntFieldUpdateOperationsInput | number
    createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type CrownHolderCreateManyInput = {
    id?: number
    groupId: string
    artistId: string
    fmUsername: string
    playCount: number
    createdAt?: Date | string
}

export type CrownHolderUpdateManyMutationInput = {
    groupId?: Prisma.StringFieldUpdateOperationsInput | string
    fmUsername?: Prisma.StringFieldUpdateOperationsInput | string
    playCount?: Prisma.IntFieldUpdateOperationsInput | number
    createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type CrownHolderUncheckedUpdateManyInput = {
    id?: Prisma.IntFieldUpdateOperationsInput | number
    groupId?: Prisma.StringFieldUpdateOperationsInput | string
    artistId?: Prisma.StringFieldUpdateOperationsInput | string
    fmUsername?: Prisma.StringFieldUpdateOperationsInput | string
    playCount?: Prisma.IntFieldUpdateOperationsInput | number
    createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type CrownHolderListRelationFilter = {
    every?: Prisma.CrownHolderWhereInput
    some?: Prisma.CrownHolderWhereInput
    none?: Prisma.CrownHolderWhereInput
}

export type CrownHolderOrderByRelationAggregateInput = {
    _count?: Prisma.SortOrder
}

export type CrownHolderGroupIdArtistIdFmUsernameCompoundUniqueInput = {
    groupId: string
    artistId: string
    fmUsername: string
}

export type CrownHolderCountOrderByAggregateInput = {
    id?: Prisma.SortOrder
    groupId?: Prisma.SortOrder
    artistId?: Prisma.SortOrder
    fmUsername?: Prisma.SortOrder
    playCount?: Prisma.SortOrder
    createdAt?: Prisma.SortOrder
}

export type CrownHolderAvgOrderByAggregateInput = {
    id?: Prisma.SortOrder
    playCount?: Prisma.SortOrder
}

export type CrownHolderMaxOrderByAggregateInput = {
    id?: Prisma.SortOrder
    groupId?: Prisma.SortOrder
    artistId?: Prisma.SortOrder
    fmUsername?: Prisma.SortOrder
    playCount?: Prisma.SortOrder
    createdAt?: Prisma.SortOrder
}

export type CrownHolderMinOrderByAggregateInput = {
    id?: Prisma.SortOrder
    groupId?: Prisma.SortOrder
    artistId?: Prisma.SortOrder
    fmUsername?: Prisma.SortOrder
    playCount?: Prisma.SortOrder
    createdAt?: Prisma.SortOrder
}

export type CrownHolderSumOrderByAggregateInput = {
    id?: Prisma.SortOrder
    playCount?: Prisma.SortOrder
}

export type CrownHolderCreateNestedManyWithoutArtistInput = {
    create?: Prisma.XOR<Prisma.CrownHolderCreateWithoutArtistInput, Prisma.CrownHolderUncheckedCreateWithoutArtistInput> | Prisma.CrownHolderCreateWithoutArtistInput[] | Prisma.CrownHolderUncheckedCreateWithoutArtistInput[]
    connectOrCreate?: Prisma.CrownHolderCreateOrConnectWithoutArtistInput | Prisma.CrownHolderCreateOrConnectWithoutArtistInput[]
    createMany?: Prisma.CrownHolderCreateManyArtistInputEnvelope
    connect?: Prisma.CrownHolderWhereUniqueInput | Prisma.CrownHolderWhereUniqueInput[]
}

export type CrownHolderUncheckedCreateNestedManyWithoutArtistInput = {
    create?: Prisma.XOR<Prisma.CrownHolderCreateWithoutArtistInput, Prisma.CrownHolderUncheckedCreateWithoutArtistInput> | Prisma.CrownHolderCreateWithoutArtistInput[] | Prisma.CrownHolderUncheckedCreateWithoutArtistInput[]
    connectOrCreate?: Prisma.CrownHolderCreateOrConnectWithoutArtistInput | Prisma.CrownHolderCreateOrConnectWithoutArtistInput[]
    createMany?: Prisma.CrownHolderCreateManyArtistInputEnvelope
    connect?: Prisma.CrownHolderWhereUniqueInput | Prisma.CrownHolderWhereUniqueInput[]
}

export type CrownHolderUpdateManyWithoutArtistNestedInput = {
    create?: Prisma.XOR<Prisma.CrownHolderCreateWithoutArtistInput, Prisma.CrownHolderUncheckedCreateWithoutArtistInput> | Prisma.CrownHolderCreateWithoutArtistInput[] | Prisma.CrownHolderUncheckedCreateWithoutArtistInput[]
    connectOrCreate?: Prisma.CrownHolderCreateOrConnectWithoutArtistInput | Prisma.CrownHolderCreateOrConnectWithoutArtistInput[]
    upsert?: Prisma.CrownHolderUpsertWithWhereUniqueWithoutArtistInput | Prisma.CrownHolderUpsertWithWhereUniqueWithoutArtistInput[]
    createMany?: Prisma.CrownHolderCreateManyArtistInputEnvelope
    set?: Prisma.CrownHolderWhereUniqueInput | Prisma.CrownHolderWhereUniqueInput[]
    disconnect?: Prisma.CrownHolderWhereUniqueInput | Prisma.CrownHolderWhereUniqueInput[]
    delete?: Prisma.CrownHolderWhereUniqueInput | Prisma.CrownHolderWhereUniqueInput[]
    connect?: Prisma.CrownHolderWhereUniqueInput | Prisma.CrownHolderWhereUniqueInput[]
    update?: Prisma.CrownHolderUpdateWithWhereUniqueWithoutArtistInput | Prisma.CrownHolderUpdateWithWhereUniqueWithoutArtistInput[]
    updateMany?: Prisma.CrownHolderUpdateManyWithWhereWithoutArtistInput | Prisma.CrownHolderUpdateManyWithWhereWithoutArtistInput[]
    deleteMany?: Prisma.CrownHolderScalarWhereInput | Prisma.CrownHolderScalarWhereInput[]
}

export type CrownHolderUncheckedUpdateManyWithoutArtistNestedInput = {
    create?: Prisma.XOR<Prisma.CrownHolderCreateWithoutArtistInput, Prisma.CrownHolderUncheckedCreateWithoutArtistInput> | Prisma.CrownHolderCreateWithoutArtistInput[] | Prisma.CrownHolderUncheckedCreateWithoutArtistInput[]
    connectOrCreate?: Prisma.CrownHolderCreateOrConnectWithoutArtistInput | Prisma.CrownHolderCreateOrConnectWithoutArtistInput[]
    upsert?: Prisma.CrownHolderUpsertWithWhereUniqueWithoutArtistInput | Prisma.CrownHolderUpsertWithWhereUniqueWithoutArtistInput[]
    createMany?: Prisma.CrownHolderCreateManyArtistInputEnvelope
    set?: Prisma.CrownHolderWhereUniqueInput | Prisma.CrownHolderWhereUniqueInput[]
    disconnect?: Prisma.CrownHolderWhereUniqueInput | Prisma.CrownHolderWhereUniqueInput[]
    delete?: Prisma.CrownHolderWhereUniqueInput | Prisma.CrownHolderWhereUniqueInput[]
    connect?: Prisma.CrownHolderWhereUniqueInput | Prisma.CrownHolderWhereUniqueInput[]
    update?: Prisma.CrownHolderUpdateWithWhereUniqueWithoutArtistInput | Prisma.CrownHolderUpdateWithWhereUniqueWithoutArtistInput[]
    updateMany?: Prisma.CrownHolderUpdateManyWithWhereWithoutArtistInput | Prisma.CrownHolderUpdateManyWithWhereWithoutArtistInput[]
    deleteMany?: Prisma.CrownHolderScalarWhereInput | Prisma.CrownHolderScalarWhereInput[]
}

export type CrownHolderCreateWithoutArtistInput = {
    groupId: string
    fmUsername: string
    playCount: number
    createdAt?: Date | string
}

export type CrownHolderUncheckedCreateWithoutArtistInput = {
    id?: number
    groupId: string
    fmUsername: string
    playCount: number
    createdAt?: Date | string
}

export type CrownHolderCreateOrConnectWithoutArtistInput = {
    where: Prisma.CrownHolderWhereUniqueInput
    create: Prisma.XOR<Prisma.CrownHolderCreateWithoutArtistInput, Prisma.CrownHolderUncheckedCreateWithoutArtistInput>
}

export type CrownHolderCreateManyArtistInputEnvelope = {
    data: Prisma.CrownHolderCreateManyArtistInput | Prisma.CrownHolderCreateManyArtistInput[]
    skipDuplicates?: boolean
}

export type CrownHolderUpsertWithWhereUniqueWithoutArtistInput = {
    where: Prisma.CrownHolderWhereUniqueInput
    update: Prisma.XOR<Prisma.CrownHolderUpdateWithoutArtistInput, Prisma.CrownHolderUncheckedUpdateWithoutArtistInput>
    create: Prisma.XOR<Prisma.CrownHolderCreateWithoutArtistInput, Prisma.CrownHolderUncheckedCreateWithoutArtistInput>
}

export type CrownHolderUpdateWithWhereUniqueWithoutArtistInput = {
    where: Prisma.CrownHolderWhereUniqueInput
    data: Prisma.XOR<Prisma.CrownHolderUpdateWithoutArtistInput, Prisma.CrownHolderUncheckedUpdateWithoutArtistInput>
}

export type CrownHolderUpdateManyWithWhereWithoutArtistInput = {
    where: Prisma.CrownHolderScalarWhereInput
    data: Prisma.XOR<Prisma.CrownHolderUpdateManyMutationInput, Prisma.CrownHolderUncheckedUpdateManyWithoutArtistInput>
}

export type CrownHolderScalarWhereInput = {
    AND?: Prisma.CrownHolderScalarWhereInput | Prisma.CrownHolderScalarWhereInput[]
    OR?: Prisma.CrownHolderScalarWhereInput[]
    NOT?: Prisma.CrownHolderScalarWhereInput | Prisma.CrownHolderScalarWhereInput[]
    id?: Prisma.IntFilter<"CrownHolder"> | number
    groupId?: Prisma.StringFilter<"CrownHolder"> | string
    artistId?: Prisma.StringFilter<"CrownHolder"> | string
    fmUsername?: Prisma.StringFilter<"CrownHolder"> | string
    playCount?: Prisma.IntFilter<"CrownHolder"> | number
    createdAt?: Prisma.DateTimeFilter<"CrownHolder"> | Date | string
}

export type CrownHolderCreateManyArtistInput = {
    id?: number
    groupId: string
    fmUsername: string
    playCount: number
    createdAt?: Date | string
}

export type CrownHolderUpdateWithoutArtistInput = {
    groupId?: Prisma.StringFieldUpdateOperationsInput | string
    fmUsername?: Prisma.StringFieldUpdateOperationsInput | string
    playCount?: Prisma.IntFieldUpdateOperationsInput | number
    createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type CrownHolderUncheckedUpdateWithoutArtistInput = {
    id?: Prisma.IntFieldUpdateOperationsInput | number
    groupId?: Prisma.StringFieldUpdateOperationsInput | string
    fmUsername?: Prisma.StringFieldUpdateOperationsInput | string
    playCount?: Prisma.IntFieldUpdateOperationsInput | number
    createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type CrownHolderUncheckedUpdateManyWithoutArtistInput = {
    id?: Prisma.IntFieldUpdateOperationsInput | number
    groupId?: Prisma.StringFieldUpdateOperationsInput | string
    fmUsername?: Prisma.StringFieldUpdateOperationsInput | string
    playCount?: Prisma.IntFieldUpdateOperationsInput | number
    createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}


export type CrownHolderSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
    id?: boolean
    groupId?: boolean
    artistId?: boolean
    fmUsername?: boolean
    playCount?: boolean
    createdAt?: boolean
    artist?: boolean | Prisma.ArtistDefaultArgs<ExtArgs>
}, ExtArgs["result"]["crownHolder"]>

export type CrownHolderSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
    id?: boolean
    groupId?: boolean
    artistId?: boolean
    fmUsername?: boolean
    playCount?: boolean
    createdAt?: boolean
    artist?: boolean | Prisma.ArtistDefaultArgs<ExtArgs>
}, ExtArgs["result"]["crownHolder"]>

export type CrownHolderSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
    id?: boolean
    groupId?: boolean
    artistId?: boolean
    fmUsername?: boolean
    playCount?: boolean
    createdAt?: boolean
    artist?: boolean | Prisma.ArtistDefaultArgs<ExtArgs>
}, ExtArgs["result"]["crownHolder"]>

export type CrownHolderSelectScalar = {
    id?: boolean
    groupId?: boolean
    artistId?: boolean
    fmUsername?: boolean
    playCount?: boolean
    createdAt?: boolean
}

export type CrownHolderOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "groupId" | "artistId" | "fmUsername" | "playCount" | "createdAt", ExtArgs["result"]["crownHolder"]>
export type CrownHolderInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
    artist?: boolean | Prisma.ArtistDefaultArgs<ExtArgs>
}
export type CrownHolderIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
    artist?: boolean | Prisma.ArtistDefaultArgs<ExtArgs>
}
export type CrownHolderIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
    artist?: boolean | Prisma.ArtistDefaultArgs<ExtArgs>
}

export type $CrownHolderPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
    name: "CrownHolder"
    objects: {
        artist: Prisma.$ArtistPayload<ExtArgs>
    }
    scalars: runtime.Types.Extensions.GetPayloadResult<{
        id: number
        groupId: string
        artistId: string
        fmUsername: string
        playCount: number
        createdAt: Date
    }, ExtArgs["result"]["crownHolder"]>
    composites: {}
}

export type CrownHolderGetPayload<S extends boolean | null | undefined | CrownHolderDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$CrownHolderPayload, S>

export type CrownHolderCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
    Omit<CrownHolderFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: CrownHolderCountAggregateInputType | true
}

export interface CrownHolderDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
    /**
     * Fields of the CrownHolder model
     */
    readonly fields: CrownHolderFieldRefs;

    [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['CrownHolder'], meta: { name: 'CrownHolder' } }

    /**
     * Find zero or one CrownHolder that matches the filter.
     * @param {CrownHolderFindUniqueArgs} args - Arguments to find a CrownHolder
     * @example
     * // Get one CrownHolder
     * const crownHolder = await prisma.crownHolder.findUnique({
     *   where: {
     *     // ... provide filter here
     *   }
     * })
     */
    findUnique<T extends CrownHolderFindUniqueArgs>(args: Prisma.SelectSubset<T, CrownHolderFindUniqueArgs<ExtArgs>>): Prisma.Prisma__CrownHolderClient<runtime.Types.Result.GetResult<Prisma.$CrownHolderPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

    /**
     * Find one CrownHolder that matches the filter or throw an error with `error.code='P2025'`
     * if no matches were found.
     * @param {CrownHolderFindUniqueOrThrowArgs} args - Arguments to find a CrownHolder
     * @example
     * // Get one CrownHolder
     * const crownHolder = await prisma.crownHolder.findUniqueOrThrow({
     *   where: {
     *     // ... provide filter here
     *   }
     * })
     */
    findUniqueOrThrow<T extends CrownHolderFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, CrownHolderFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__CrownHolderClient<runtime.Types.Result.GetResult<Prisma.$CrownHolderPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

    /**
     * Find the first CrownHolder that matches the filter.
     * Note, that providing `undefined` is treated as the value not being there.
     * Read more here: https://pris.ly/d/null-undefined
     * @param {CrownHolderFindFirstArgs} args - Arguments to find a CrownHolder
     * @example
     * // Get one CrownHolder
     * const crownHolder = await prisma.crownHolder.findFirst({
     *   where: {
     *     // ... provide filter here
     *   }
     * })
     */
    findFirst<T extends CrownHolderFindFirstArgs>(args?: Prisma.SelectSubset<T, CrownHolderFindFirstArgs<ExtArgs>>): Prisma.Prisma__CrownHolderClient<runtime.Types.Result.GetResult<Prisma.$CrownHolderPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

    /**
     * Find the first CrownHolder that matches the filter or
     * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
     * Note, that providing `undefined` is treated as the value not being there.
     * Read more here: https://pris.ly/d/null-undefined
     * @param {CrownHolderFindFirstOrThrowArgs} args - Arguments to find a CrownHolder
     * @example
     * // Get one CrownHolder
     * const crownHolder = await prisma.crownHolder.findFirstOrThrow({
     *   where: {
     *     // ... provide filter here
     *   }
     * })
     */
    findFirstOrThrow<T extends CrownHolderFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, CrownHolderFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__CrownHolderClient<runtime.Types.Result.GetResult<Prisma.$CrownHolderPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

    /**
     * Find zero or more CrownHolders that matches the filter.
     * Note, that providing `undefined` is treated as the value not being there.
     * Read more here: https://pris.ly/d/null-undefined
     * @param {CrownHolderFindManyArgs} args - Arguments to filter and select certain fields only.
     * @example
     * // Get all CrownHolders
     * const crownHolders = await prisma.crownHolder.findMany()
     *
     * // Get first 10 CrownHolders
     * const crownHolders = await prisma.crownHolder.findMany({ take: 10 })
     *
     * // Only select the `id`
     * const crownHolderWithIdOnly = await prisma.crownHolder.findMany({ select: { id: true } })
     *
     */
    findMany<T extends CrownHolderFindManyArgs>(args?: Prisma.SelectSubset<T, CrownHolderFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$CrownHolderPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

    /**
     * Create a CrownHolder.
     * @param {CrownHolderCreateArgs} args - Arguments to create a CrownHolder.
     * @example
     * // Create one CrownHolder
     * const CrownHolder = await prisma.crownHolder.create({
     *   data: {
     *     // ... data to create a CrownHolder
     *   }
     * })
     *
     */
    create<T extends CrownHolderCreateArgs>(args: Prisma.SelectSubset<T, CrownHolderCreateArgs<ExtArgs>>): Prisma.Prisma__CrownHolderClient<runtime.Types.Result.GetResult<Prisma.$CrownHolderPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

    /**
     * Create many CrownHolders.
     * @param {CrownHolderCreateManyArgs} args - Arguments to create many CrownHolders.
     * @example
     * // Create many CrownHolders
     * const crownHolder = await prisma.crownHolder.createMany({
     *   data: [
     *     // ... provide data here
     *   ]
     * })
     *
     */
    createMany<T extends CrownHolderCreateManyArgs>(args?: Prisma.SelectSubset<T, CrownHolderCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

    /**
     * Create many CrownHolders and returns the data saved in the database.
     * @param {CrownHolderCreateManyAndReturnArgs} args - Arguments to create many CrownHolders.
     * @example
     * // Create many CrownHolders
     * const crownHolder = await prisma.crownHolder.createManyAndReturn({
     *   data: [
     *     // ... provide data here
     *   ]
     * })
     *
     * // Create many CrownHolders and only return the `id`
     * const crownHolderWithIdOnly = await prisma.crownHolder.createManyAndReturn({
     *   select: { id: true },
     *   data: [
     *     // ... provide data here
     *   ]
     * })
     * Note, that providing `undefined` is treated as the value not being there.
     * Read more here: https://pris.ly/d/null-undefined
     *
     */
    createManyAndReturn<T extends CrownHolderCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, CrownHolderCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$CrownHolderPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

    /**
     * Delete a CrownHolder.
     * @param {CrownHolderDeleteArgs} args - Arguments to delete one CrownHolder.
     * @example
     * // Delete one CrownHolder
     * const CrownHolder = await prisma.crownHolder.delete({
     *   where: {
     *     // ... filter to delete one CrownHolder
     *   }
     * })
     *
     */
    delete<T extends CrownHolderDeleteArgs>(args: Prisma.SelectSubset<T, CrownHolderDeleteArgs<ExtArgs>>): Prisma.Prisma__CrownHolderClient<runtime.Types.Result.GetResult<Prisma.$CrownHolderPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

    /**
     * Update one CrownHolder.
     * @param {CrownHolderUpdateArgs} args - Arguments to update one CrownHolder.
     * @example
     * // Update one CrownHolder
     * const crownHolder = await prisma.crownHolder.update({
     *   where: {
     *     // ... provide filter here
     *   },
     *   data: {
     *     // ... provide data here
     *   }
     * })
     *
     */
    update<T extends CrownHolderUpdateArgs>(args: Prisma.SelectSubset<T, CrownHolderUpdateArgs<ExtArgs>>): Prisma.Prisma__CrownHolderClient<runtime.Types.Result.GetResult<Prisma.$CrownHolderPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

    /**
     * Delete zero or more CrownHolders.
     * @param {CrownHolderDeleteManyArgs} args - Arguments to filter CrownHolders to delete.
     * @example
     * // Delete a few CrownHolders
     * const { count } = await prisma.crownHolder.deleteMany({
     *   where: {
     *     // ... provide filter here
     *   }
     * })
     *
     */
    deleteMany<T extends CrownHolderDeleteManyArgs>(args?: Prisma.SelectSubset<T, CrownHolderDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

    /**
     * Update zero or more CrownHolders.
     * Note, that providing `undefined` is treated as the value not being there.
     * Read more here: https://pris.ly/d/null-undefined
     * @param {CrownHolderUpdateManyArgs} args - Arguments to update one or more rows.
     * @example
     * // Update many CrownHolders
     * const crownHolder = await prisma.crownHolder.updateMany({
     *   where: {
     *     // ... provide filter here
     *   },
     *   data: {
     *     // ... provide data here
     *   }
     * })
     *
     */
    updateMany<T extends CrownHolderUpdateManyArgs>(args: Prisma.SelectSubset<T, CrownHolderUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

    /**
     * Update zero or more CrownHolders and returns the data updated in the database.
     * @param {CrownHolderUpdateManyAndReturnArgs} args - Arguments to update many CrownHolders.
     * @example
     * // Update many CrownHolders
     * const crownHolder = await prisma.crownHolder.updateManyAndReturn({
     *   where: {
     *     // ... provide filter here
     *   },
     *   data: [
     *     // ... provide data here
     *   ]
     * })
     *
     * // Update zero or more CrownHolders and only return the `id`
     * const crownHolderWithIdOnly = await prisma.crownHolder.updateManyAndReturn({
     *   select: { id: true },
     *   where: {
     *     // ... provide filter here
     *   },
     *   data: [
     *     // ... provide data here
     *   ]
     * })
     * Note, that providing `undefined` is treated as the value not being there.
     * Read more here: https://pris.ly/d/null-undefined
     *
     */
    updateManyAndReturn<T extends CrownHolderUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, CrownHolderUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$CrownHolderPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

    /**
     * Create or update one CrownHolder.
     * @param {CrownHolderUpsertArgs} args - Arguments to update or create a CrownHolder.
     * @example
     * // Update or create a CrownHolder
     * const crownHolder = await prisma.crownHolder.upsert({
     *   create: {
     *     // ... data to create a CrownHolder
     *   },
     *   update: {
     *     // ... in case it already exists, update
     *   },
     *   where: {
     *     // ... the filter for the CrownHolder we want to update
     *   }
     * })
     */
    upsert<T extends CrownHolderUpsertArgs>(args: Prisma.SelectSubset<T, CrownHolderUpsertArgs<ExtArgs>>): Prisma.Prisma__CrownHolderClient<runtime.Types.Result.GetResult<Prisma.$CrownHolderPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

    /**
     * Count the number of CrownHolders.
     * Note, that providing `undefined` is treated as the value not being there.
     * Read more here: https://pris.ly/d/null-undefined
     * @param {CrownHolderCountArgs} args - Arguments to filter CrownHolders to count.
     * @example
     * // Count the number of CrownHolders
     * const count = await prisma.crownHolder.count({
     *   where: {
     *     // ... the filter for the CrownHolders we want to count
     *   }
     * })
     **/
    count<T extends CrownHolderCountArgs>(
        args?: Prisma.Subset<T, CrownHolderCountArgs>,
    ): Prisma.PrismaPromise<
        T extends runtime.Types.Utils.Record<'select', any>
            ? T['select'] extends true
                ? number
                : Prisma.GetScalarType<T['select'], CrownHolderCountAggregateOutputType>
            : number
    >

    /**
     * Allows you to perform aggregations operations on a CrownHolder.
     * Note, that providing `undefined` is treated as the value not being there.
     * Read more here: https://pris.ly/d/null-undefined
     * @param {CrownHolderAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
     * @example
     * // Ordered by age ascending
     * // Where email contains prisma.io
     * // Limited to the 10 users
     * const aggregations = await prisma.user.aggregate({
     *   _avg: {
     *     age: true,
     *   },
     *   where: {
     *     email: {
     *       contains: "prisma.io",
     *     },
     *   },
     *   orderBy: {
     *     age: "asc",
     *   },
     *   take: 10,
     * })
     **/
    aggregate<T extends CrownHolderAggregateArgs>(args: Prisma.Subset<T, CrownHolderAggregateArgs>): Prisma.PrismaPromise<GetCrownHolderAggregateType<T>>

    /**
     * Group by CrownHolder.
     * Note, that providing `undefined` is treated as the value not being there.
     * Read more here: https://pris.ly/d/null-undefined
     * @param {CrownHolderGroupByArgs} args - Group by arguments.
     * @example
     * // Group by city, order by createdAt, get count
     * const result = await prisma.user.groupBy({
     *   by: ['city', 'createdAt'],
     *   orderBy: {
     *     createdAt: true
     *   },
     *   _count: {
     *     _all: true
     *   },
     * })
     *
     **/
    groupBy<
        T extends CrownHolderGroupByArgs,
        HasSelectOrTake extends Prisma.Or<
            Prisma.Extends<'skip', Prisma.Keys<T>>,
            Prisma.Extends<'take', Prisma.Keys<T>>
        >,
        OrderByArg extends Prisma.True extends HasSelectOrTake
            ? { orderBy: CrownHolderGroupByArgs['orderBy'] }
            : { orderBy?: CrownHolderGroupByArgs['orderBy'] },
        OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
        ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
        ByValid extends Prisma.Has<ByFields, OrderFields>,
        HavingFields extends Prisma.GetHavingFields<T['having']>,
        HavingValid extends Prisma.Has<ByFields, HavingFields>,
        ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
        InputErrors extends ByEmpty extends Prisma.True
            ? `Error: "by" must not be empty.`
            : HavingValid extends Prisma.False
                ? {
                    [P in HavingFields]: P extends ByFields
                        ? never
                        : P extends string
                            ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
                            : [
                                Error,
                                'Field ',
                                P,
                                ` in "having" needs to be provided in "by"`,
                            ]
                }[HavingFields]
                : 'take' extends Prisma.Keys<T>
                    ? 'orderBy' extends Prisma.Keys<T>
                        ? ByValid extends Prisma.True
                            ? {}
                            : {
                                [P in OrderFields]: P extends ByFields
                                    ? never
                                    : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
                            }[OrderFields]
                        : 'Error: If you provide "take", you also need to provide "orderBy"'
                    : 'skip' extends Prisma.Keys<T>
                        ? 'orderBy' extends Prisma.Keys<T>
                            ? ByValid extends Prisma.True
                                ? {}
                                : {
                                    [P in OrderFields]: P extends ByFields
                                        ? never
                                        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
                                }[OrderFields]
                            : 'Error: If you provide "skip", you also need to provide "orderBy"'
                        : ByValid extends Prisma.True
                            ? {}
                            : {
                                [P in OrderFields]: P extends ByFields
                                    ? never
                                    : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
                            }[OrderFields]
    >(args: Prisma.SubsetIntersection<T, CrownHolderGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetCrownHolderGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
}

/**
 * The delegate class that acts as a "Promise-like" for CrownHolder.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__CrownHolderClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
    readonly [Symbol.toStringTag]: "PrismaPromise"

    artist<T extends Prisma.ArtistDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.ArtistDefaultArgs<ExtArgs>>): Prisma.Prisma__ArtistClient<runtime.Types.Result.GetResult<Prisma.$ArtistPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>

    /**
     * Attaches callbacks for the resolution and/or rejection of the Promise.
     * @param onfulfilled The callback to execute when the Promise is resolved.
     * @param onrejected The callback to execute when the Promise is rejected.
     * @returns A Promise for the completion of which ever callback is executed.
     */
    then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>

    /**
     * Attaches a callback for only the rejection of the Promise.
     * @param onrejected The callback to execute when the Promise is rejected.
     * @returns A Promise for the completion of the callback.
     */
    catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>

    /**
     * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
     * resolved value cannot be modified from the callback.
     * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
     * @returns A Promise for the completion of the callback.
     */
    finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}


/**
 * Fields of the CrownHolder model
 */
export interface CrownHolderFieldRefs {
    readonly id: Prisma.FieldRef<"CrownHolder", 'Int'>
    readonly groupId: Prisma.FieldRef<"CrownHolder", 'String'>
    readonly artistId: Prisma.FieldRef<"CrownHolder", 'String'>
    readonly fmUsername: Prisma.FieldRef<"CrownHolder", 'String'>
    readonly playCount: Prisma.FieldRef<"CrownHolder", 'Int'>
    readonly createdAt: Prisma.FieldRef<"CrownHolder", 'DateTime'>
}


// Custom InputTypes
/**
 * CrownHolder findUnique
 */
export type CrownHolderFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
    /**
     * Select specific fields to fetch from the CrownHolder
     */
    select?: Prisma.CrownHolderSelect<ExtArgs> | null
    /**
     * Omit specific fields from the CrownHolder
     */
    omit?: Prisma.CrownHolderOmit<ExtArgs> | null
    /**
     * Choose, which related nodes to fetch as well
     */
    include?: Prisma.CrownHolderInclude<ExtArgs> | null
    /**
     * Filter, which CrownHolder to fetch.
     */
    where: Prisma.CrownHolderWhereUniqueInput
}

/**
 * CrownHolder findUniqueOrThrow
 */
export type CrownHolderFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
    /**
     * Select specific fields to fetch from the CrownHolder
     */
    select?: Prisma.CrownHolderSelect<ExtArgs> | null
    /**
     * Omit specific fields from the CrownHolder
     */
    omit?: Prisma.CrownHolderOmit<ExtArgs> | null
    /**
     * Choose, which related nodes to fetch as well
     */
    include?: Prisma.CrownHolderInclude<ExtArgs> | null
    /**
     * Filter, which CrownHolder to fetch.
     */
    where: Prisma.CrownHolderWhereUniqueInput
}

/**
 * CrownHolder findFirst
 */
export type CrownHolderFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
    /**
     * Select specific fields to fetch from the CrownHolder
     */
    select?: Prisma.CrownHolderSelect<ExtArgs> | null
    /**
     * Omit specific fields from the CrownHolder
     */
    omit?: Prisma.CrownHolderOmit<ExtArgs> | null
    /**
     * Choose, which related nodes to fetch as well
     */
    include?: Prisma.CrownHolderInclude<ExtArgs> | null
    /**
     * Filter, which CrownHolder to fetch.
     */
    where?: Prisma.CrownHolderWhereInput
    /**
     * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
     *
     * Determine the order of CrownHolders to fetch.
     */
    orderBy?: Prisma.CrownHolderOrderByWithRelationInput | Prisma.CrownHolderOrderByWithRelationInput[]
    /**
     * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
     *
     * Sets the position for searching for CrownHolders.
     */
    cursor?: Prisma.CrownHolderWhereUniqueInput
    /**
     * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
     *
     * Take `±n` CrownHolders from the position of the cursor.
     */
    take?: number
    /**
     * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
     *
     * Skip the first `n` CrownHolders.
     */
    skip?: number
    /**
     * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
     *
     * Filter by unique combinations of CrownHolders.
     */
    distinct?: Prisma.CrownHolderScalarFieldEnum | Prisma.CrownHolderScalarFieldEnum[]
}

/**
 * CrownHolder findFirstOrThrow
 */
export type CrownHolderFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
    /**
     * Select specific fields to fetch from the CrownHolder
     */
    select?: Prisma.CrownHolderSelect<ExtArgs> | null
    /**
     * Omit specific fields from the CrownHolder
     */
    omit?: Prisma.CrownHolderOmit<ExtArgs> | null
    /**
     * Choose, which related nodes to fetch as well
     */
    include?: Prisma.CrownHolderInclude<ExtArgs> | null
    /**
     * Filter, which CrownHolder to fetch.
     */
    where?: Prisma.CrownHolderWhereInput
    /**
     * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
     *
     * Determine the order of CrownHolders to fetch.
     */
    orderBy?: Prisma.CrownHolderOrderByWithRelationInput | Prisma.CrownHolderOrderByWithRelationInput[]
    /**
     * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
     *
     * Sets the position for searching for CrownHolders.
     */
    cursor?: Prisma.CrownHolderWhereUniqueInput
    /**
     * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
     *
     * Take `±n` CrownHolders from the position of the cursor.
     */
    take?: number
    /**
     * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
     *
     * Skip the first `n` CrownHolders.
     */
    skip?: number
    /**
     * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
     *
     * Filter by unique combinations of CrownHolders.
     */
    distinct?: Prisma.CrownHolderScalarFieldEnum | Prisma.CrownHolderScalarFieldEnum[]
}

/**
 * CrownHolder findMany
 */
export type CrownHolderFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
    /**
     * Select specific fields to fetch from the CrownHolder
     */
    select?: Prisma.CrownHolderSelect<ExtArgs> | null
    /**
     * Omit specific fields from the CrownHolder
     */
    omit?: Prisma.CrownHolderOmit<ExtArgs> | null
    /**
     * Choose, which related nodes to fetch as well
     */
    include?: Prisma.CrownHolderInclude<ExtArgs> | null
    /**
     * Filter, which CrownHolders to fetch.
     */
    where?: Prisma.CrownHolderWhereInput
    /**
     * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
     *
     * Determine the order of CrownHolders to fetch.
     */
    orderBy?: Prisma.CrownHolderOrderByWithRelationInput | Prisma.CrownHolderOrderByWithRelationInput[]
    /**
     * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
     *
     * Sets the position for listing CrownHolders.
     */
    cursor?: Prisma.CrownHolderWhereUniqueInput
    /**
     * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
     *
     * Take `±n` CrownHolders from the position of the cursor.
     */
    take?: number
    /**
     * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
     *
     * Skip the first `n` CrownHolders.
     */
    skip?: number
    distinct?: Prisma.CrownHolderScalarFieldEnum | Prisma.CrownHolderScalarFieldEnum[]
}

/**
 * CrownHolder create
 */
export type CrownHolderCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
    /**
     * Select specific fields to fetch from the CrownHolder
     */
    select?: Prisma.CrownHolderSelect<ExtArgs> | null
    /**
     * Omit specific fields from the CrownHolder
     */
    omit?: Prisma.CrownHolderOmit<ExtArgs> | null
    /**
     * Choose, which related nodes to fetch as well
     */
    include?: Prisma.CrownHolderInclude<ExtArgs> | null
    /**
     * The data needed to create a CrownHolder.
     */
    data: Prisma.XOR<Prisma.CrownHolderCreateInput, Prisma.CrownHolderUncheckedCreateInput>
}

/**
 * CrownHolder createMany
 */
export type CrownHolderCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
    /**
     * The data used to create many CrownHolders.
     */
    data: Prisma.CrownHolderCreateManyInput | Prisma.CrownHolderCreateManyInput[]
    skipDuplicates?: boolean
}

/**
 * CrownHolder createManyAndReturn
 */
export type CrownHolderCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
    /**
     * Select specific fields to fetch from the CrownHolder
     */
    select?: Prisma.CrownHolderSelectCreateManyAndReturn<ExtArgs> | null
    /**
     * Omit specific fields from the CrownHolder
     */
    omit?: Prisma.CrownHolderOmit<ExtArgs> | null
    /**
     * The data used to create many CrownHolders.
     */
    data: Prisma.CrownHolderCreateManyInput | Prisma.CrownHolderCreateManyInput[]
    skipDuplicates?: boolean
    /**
     * Choose, which related nodes to fetch as well
     */
    include?: Prisma.CrownHolderIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * CrownHolder update
 */
export type CrownHolderUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
    /**
     * Select specific fields to fetch from the CrownHolder
     */
    select?: Prisma.CrownHolderSelect<ExtArgs> | null
    /**
     * Omit specific fields from the CrownHolder
     */
    omit?: Prisma.CrownHolderOmit<ExtArgs> | null
    /**
     * Choose, which related nodes to fetch as well
     */
    include?: Prisma.CrownHolderInclude<ExtArgs> | null
    /**
     * The data needed to update a CrownHolder.
     */
    data: Prisma.XOR<Prisma.CrownHolderUpdateInput, Prisma.CrownHolderUncheckedUpdateInput>
    /**
     * Choose, which CrownHolder to update.
     */
    where: Prisma.CrownHolderWhereUniqueInput
}

/**
 * CrownHolder updateMany
 */
export type CrownHolderUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
    /**
     * The data used to update CrownHolders.
     */
    data: Prisma.XOR<Prisma.CrownHolderUpdateManyMutationInput, Prisma.CrownHolderUncheckedUpdateManyInput>
    /**
     * Filter which CrownHolders to update
     */
    where?: Prisma.CrownHolderWhereInput
    /**
     * Limit how many CrownHolders to update.
     */
    limit?: number
}

/**
 * CrownHolder updateManyAndReturn
 */
export type CrownHolderUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
    /**
     * Select specific fields to fetch from the CrownHolder
     */
    select?: Prisma.CrownHolderSelectUpdateManyAndReturn<ExtArgs> | null
    /**
     * Omit specific fields from the CrownHolder
     */
    omit?: Prisma.CrownHolderOmit<ExtArgs> | null
    /**
     * The data used to update CrownHolders.
     */
    data: Prisma.XOR<Prisma.CrownHolderUpdateManyMutationInput, Prisma.CrownHolderUncheckedUpdateManyInput>
    /**
     * Filter which CrownHolders to update
     */
    where?: Prisma.CrownHolderWhereInput
    /**
     * Limit how many CrownHolders to update.
     */
    limit?: number
    /**
     * Choose, which related nodes to fetch as well
     */
    include?: Prisma.CrownHolderIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * CrownHolder upsert
 */
export type CrownHolderUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
    /**
     * Select specific fields to fetch from the CrownHolder
     */
    select?: Prisma.CrownHolderSelect<ExtArgs> | null
    /**
     * Omit specific fields from the CrownHolder
     */
    omit?: Prisma.CrownHolderOmit<ExtArgs> | null
    /**
     * Choose, which related nodes to fetch as well
     */
    include?: Prisma.CrownHolderInclude<ExtArgs> | null
    /**
     * The filter to search for the CrownHolder to update in case it exists.
     */
    where: Prisma.CrownHolderWhereUniqueInput
    /**
     * In case the CrownHolder found by the `where` argument doesn't exist, create a new CrownHolder with this data.
     */
    create: Prisma.XOR<Prisma.CrownHolderCreateInput, Prisma.CrownHolderUncheckedCreateInput>
    /**
     * In case the CrownHolder was found with the provided `where` argument, update it with this data.
     */
    update: Prisma.XOR<Prisma.CrownHolderUpdateInput, Prisma.CrownHolderUncheckedUpdateInput>
}

/**
 * CrownHolder delete
 */
export type CrownHolderDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
    /**
     * Select specific fields to fetch from the CrownHolder
     */
    select?: Prisma.CrownHolderSelect<ExtArgs> | null
    /**
     * Omit specific fields from the CrownHolder
     */
    omit?: Prisma.CrownHolderOmit<ExtArgs> | null
    /**
     * Choose, which related nodes to fetch as well
     */
    include?: Prisma.CrownHolderInclude<ExtArgs> | null
    /**
     * Filter which CrownHolder to delete.
     */
    where: Prisma.CrownHolderWhereUniqueInput
}

/**
 * CrownHolder deleteMany
 */
export type CrownHolderDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
    /**
     * Filter which CrownHolders to delete
     */
    where?: Prisma.CrownHolderWhereInput
    /**
     * Limit how many CrownHolders to delete.
     */
    limit?: number
}

/**
 * CrownHolder without action
 */
export type CrownHolderDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
    /**
     * Select specific fields to fetch from the CrownHolder
     */
    select?: Prisma.CrownHolderSelect<ExtArgs> | null
    /**
     * Omit specific fields from the CrownHolder
     */
    omit?: Prisma.CrownHolderOmit<ExtArgs> | null
    /**
     * Choose, which related nodes to fetch as well
     */
    include?: Prisma.CrownHolderInclude<ExtArgs> | null
}
