/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck
/*
 * This file exports the `Crown` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model Crown
 *
 */
export type CrownModel = runtime.Types.Result.DefaultSelection<Prisma.$CrownPayload>

export type AggregateCrown = {
    _count: CrownCountAggregateOutputType | null
    _avg: CrownAvgAggregateOutputType | null
    _sum: CrownSumAggregateOutputType | null
    _min: CrownMinAggregateOutputType | null
    _max: CrownMaxAggregateOutputType | null
}

export type CrownAvgAggregateOutputType = {
    id: number | null
    playCount: number | null
    switchedTimes: number | null
}

export type CrownSumAggregateOutputType = {
    id: number | null
    playCount: number | null
    switchedTimes: number | null
}

export type CrownMinAggregateOutputType = {
    id: number | null
    groupId: string | null
    artistId: string | null
    fmUsername: string | null
    playCount: number | null
    switchedTimes: number | null
    createdAt: Date | null
    updatedAt: Date | null
}

export type CrownMaxAggregateOutputType = {
    id: number | null
    groupId: string | null
    artistId: string | null
    fmUsername: string | null
    playCount: number | null
    switchedTimes: number | null
    createdAt: Date | null
    updatedAt: Date | null
}

export type CrownCountAggregateOutputType = {
    id: number
    groupId: number
    artistId: number
    fmUsername: number
    playCount: number
    switchedTimes: number
    createdAt: number
    updatedAt: number
    _all: number
}


export type CrownAvgAggregateInputType = {
    id?: true
    playCount?: true
    switchedTimes?: true
}

export type CrownSumAggregateInputType = {
    id?: true
    playCount?: true
    switchedTimes?: true
}

export type CrownMinAggregateInputType = {
    id?: true
    groupId?: true
    artistId?: true
    fmUsername?: true
    playCount?: true
    switchedTimes?: true
    createdAt?: true
    updatedAt?: true
}

export type CrownMaxAggregateInputType = {
    id?: true
    groupId?: true
    artistId?: true
    fmUsername?: true
    playCount?: true
    switchedTimes?: true
    createdAt?: true
    updatedAt?: true
}

export type CrownCountAggregateInputType = {
    id?: true
    groupId?: true
    artistId?: true
    fmUsername?: true
    playCount?: true
    switchedTimes?: true
    createdAt?: true
    updatedAt?: true
    _all?: true
}

export type CrownAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
    /**
     * Filter which Crown to aggregate.
     */
    where?: Prisma.CrownWhereInput
    /**
     * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
     *
     * Determine the order of Crowns to fetch.
     */
    orderBy?: Prisma.CrownOrderByWithRelationInput | Prisma.CrownOrderByWithRelationInput[]
    /**
     * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
     *
     * Sets the start position
     */
    cursor?: Prisma.CrownWhereUniqueInput
    /**
     * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
     *
     * Take `±n` Crowns from the position of the cursor.
     */
    take?: number
    /**
     * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
     *
     * Skip the first `n` Crowns.
     */
    skip?: number
    /**
     * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
     *
     * Count returned Crowns
     **/
    _count?: true | CrownCountAggregateInputType
    /**
     * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
     *
     * Select which fields to average
     **/
    _avg?: CrownAvgAggregateInputType
    /**
     * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
     *
     * Select which fields to sum
     **/
    _sum?: CrownSumAggregateInputType
    /**
     * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
     *
     * Select which fields to find the minimum value
     **/
    _min?: CrownMinAggregateInputType
    /**
     * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
     *
     * Select which fields to find the maximum value
     **/
    _max?: CrownMaxAggregateInputType
}

export type GetCrownAggregateType<T extends CrownAggregateArgs> = {
    [P in keyof T & keyof AggregateCrown]: P extends '_count' | 'count'
        ? T[P] extends true
            ? number
            : Prisma.GetScalarType<T[P], AggregateCrown[P]>
        : Prisma.GetScalarType<T[P], AggregateCrown[P]>
}


export type CrownGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
    where?: Prisma.CrownWhereInput
    orderBy?: Prisma.CrownOrderByWithAggregationInput | Prisma.CrownOrderByWithAggregationInput[]
    by: Prisma.CrownScalarFieldEnum[] | Prisma.CrownScalarFieldEnum
    having?: Prisma.CrownScalarWhereWithAggregatesInput
    take?: number
    skip?: number
    _count?: CrownCountAggregateInputType | true
    _avg?: CrownAvgAggregateInputType
    _sum?: CrownSumAggregateInputType
    _min?: CrownMinAggregateInputType
    _max?: CrownMaxAggregateInputType
}

export type CrownGroupByOutputType = {
    id: number
    groupId: string
    artistId: string
    fmUsername: string
    playCount: number
    switchedTimes: number
    createdAt: Date
    updatedAt: Date
    _count: CrownCountAggregateOutputType | null
    _avg: CrownAvgAggregateOutputType | null
    _sum: CrownSumAggregateOutputType | null
    _min: CrownMinAggregateOutputType | null
    _max: CrownMaxAggregateOutputType | null
}

type GetCrownGroupByPayload<T extends CrownGroupByArgs> = Prisma.PrismaPromise<
    Array<
        Prisma.PickEnumerable<CrownGroupByOutputType, T['by']> &
        {
            [P in ((keyof T) & (keyof CrownGroupByOutputType))]: P extends '_count'
            ? T[P] extends boolean
                ? number
                : Prisma.GetScalarType<T[P], CrownGroupByOutputType[P]>
            : Prisma.GetScalarType<T[P], CrownGroupByOutputType[P]>
        }
    >
>


export type CrownWhereInput = {
    AND?: Prisma.CrownWhereInput | Prisma.CrownWhereInput[]
    OR?: Prisma.CrownWhereInput[]
    NOT?: Prisma.CrownWhereInput | Prisma.CrownWhereInput[]
    id?: Prisma.IntFilter<"Crown"> | number
    groupId?: Prisma.StringFilter<"Crown"> | string
    artistId?: Prisma.StringFilter<"Crown"> | string
    fmUsername?: Prisma.StringFilter<"Crown"> | string
    playCount?: Prisma.IntFilter<"Crown"> | number
    switchedTimes?: Prisma.IntFilter<"Crown"> | number
    createdAt?: Prisma.DateTimeFilter<"Crown"> | Date | string
    updatedAt?: Prisma.DateTimeFilter<"Crown"> | Date | string
    artist?: Prisma.XOR<Prisma.ArtistScalarRelationFilter, Prisma.ArtistWhereInput>
}

export type CrownOrderByWithRelationInput = {
    id?: Prisma.SortOrder
    groupId?: Prisma.SortOrder
    artistId?: Prisma.SortOrder
    fmUsername?: Prisma.SortOrder
    playCount?: Prisma.SortOrder
    switchedTimes?: Prisma.SortOrder
    createdAt?: Prisma.SortOrder
    updatedAt?: Prisma.SortOrder
    artist?: Prisma.ArtistOrderByWithRelationInput
}

export type CrownWhereUniqueInput = Prisma.AtLeast<{
    id?: number
    groupId_artistId?: Prisma.CrownGroupIdArtistIdCompoundUniqueInput
    AND?: Prisma.CrownWhereInput | Prisma.CrownWhereInput[]
    OR?: Prisma.CrownWhereInput[]
    NOT?: Prisma.CrownWhereInput | Prisma.CrownWhereInput[]
    groupId?: Prisma.StringFilter<"Crown"> | string
    artistId?: Prisma.StringFilter<"Crown"> | string
    fmUsername?: Prisma.StringFilter<"Crown"> | string
    playCount?: Prisma.IntFilter<"Crown"> | number
    switchedTimes?: Prisma.IntFilter<"Crown"> | number
    createdAt?: Prisma.DateTimeFilter<"Crown"> | Date | string
    updatedAt?: Prisma.DateTimeFilter<"Crown"> | Date | string
    artist?: Prisma.XOR<Prisma.ArtistScalarRelationFilter, Prisma.ArtistWhereInput>
}, "id" | "groupId_artistId">

export type CrownOrderByWithAggregationInput = {
    id?: Prisma.SortOrder
    groupId?: Prisma.SortOrder
    artistId?: Prisma.SortOrder
    fmUsername?: Prisma.SortOrder
    playCount?: Prisma.SortOrder
    switchedTimes?: Prisma.SortOrder
    createdAt?: Prisma.SortOrder
    updatedAt?: Prisma.SortOrder
    _count?: Prisma.CrownCountOrderByAggregateInput
    _avg?: Prisma.CrownAvgOrderByAggregateInput
    _max?: Prisma.CrownMaxOrderByAggregateInput
    _min?: Prisma.CrownMinOrderByAggregateInput
    _sum?: Prisma.CrownSumOrderByAggregateInput
}

export type CrownScalarWhereWithAggregatesInput = {
    AND?: Prisma.CrownScalarWhereWithAggregatesInput | Prisma.CrownScalarWhereWithAggregatesInput[]
    OR?: Prisma.CrownScalarWhereWithAggregatesInput[]
    NOT?: Prisma.CrownScalarWhereWithAggregatesInput | Prisma.CrownScalarWhereWithAggregatesInput[]
    id?: Prisma.IntWithAggregatesFilter<"Crown"> | number
    groupId?: Prisma.StringWithAggregatesFilter<"Crown"> | string
    artistId?: Prisma.StringWithAggregatesFilter<"Crown"> | string
    fmUsername?: Prisma.StringWithAggregatesFilter<"Crown"> | string
    playCount?: Prisma.IntWithAggregatesFilter<"Crown"> | number
    switchedTimes?: Prisma.IntWithAggregatesFilter<"Crown"> | number
    createdAt?: Prisma.DateTimeWithAggregatesFilter<"Crown"> | Date | string
    updatedAt?: Prisma.DateTimeWithAggregatesFilter<"Crown"> | Date | string
}

export type CrownCreateInput = {
    groupId: string
    fmUsername: string
    playCount: number
    switchedTimes?: number
    createdAt?: Date | string
    updatedAt?: Date | string
    artist: Prisma.ArtistCreateNestedOneWithoutCrownsInput
}

export type CrownUncheckedCreateInput = {
    id?: number
    groupId: string
    artistId: string
    fmUsername: string
    playCount: number
    switchedTimes?: number
    createdAt?: Date | string
    updatedAt?: Date | string
}

export type CrownUpdateInput = {
    groupId?: Prisma.StringFieldUpdateOperationsInput | string
    fmUsername?: Prisma.StringFieldUpdateOperationsInput | string
    playCount?: Prisma.IntFieldUpdateOperationsInput | number
    switchedTimes?: Prisma.IntFieldUpdateOperationsInput | number
    createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
    updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
    artist?: Prisma.ArtistUpdateOneRequiredWithoutCrownsNestedInput
}

export type CrownUncheckedUpdateInput = {
    id?: Prisma.IntFieldUpdateOperationsInput | number
    groupId?: Prisma.StringFieldUpdateOperationsInput | string
    artistId?: Prisma.StringFieldUpdateOperationsInput | string
    fmUsername?: Prisma.StringFieldUpdateOperationsInput | string
    playCount?: Prisma.IntFieldUpdateOperationsInput | number
    switchedTimes?: Prisma.IntFieldUpdateOperationsInput | number
    createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
    updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type CrownCreateManyInput = {
    id?: number
    groupId: string
    artistId: string
    fmUsername: string
    playCount: number
    switchedTimes?: number
    createdAt?: Date | string
    updatedAt?: Date | string
}

export type CrownUpdateManyMutationInput = {
    groupId?: Prisma.StringFieldUpdateOperationsInput | string
    fmUsername?: Prisma.StringFieldUpdateOperationsInput | string
    playCount?: Prisma.IntFieldUpdateOperationsInput | number
    switchedTimes?: Prisma.IntFieldUpdateOperationsInput | number
    createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
    updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type CrownUncheckedUpdateManyInput = {
    id?: Prisma.IntFieldUpdateOperationsInput | number
    groupId?: Prisma.StringFieldUpdateOperationsInput | string
    artistId?: Prisma.StringFieldUpdateOperationsInput | string
    fmUsername?: Prisma.StringFieldUpdateOperationsInput | string
    playCount?: Prisma.IntFieldUpdateOperationsInput | number
    switchedTimes?: Prisma.IntFieldUpdateOperationsInput | number
    createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
    updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type CrownListRelationFilter = {
    every?: Prisma.CrownWhereInput
    some?: Prisma.CrownWhereInput
    none?: Prisma.CrownWhereInput
}

export type CrownOrderByRelationAggregateInput = {
    _count?: Prisma.SortOrder
}

export type CrownGroupIdArtistIdCompoundUniqueInput = {
    groupId: string
    artistId: string
}

export type CrownCountOrderByAggregateInput = {
    id?: Prisma.SortOrder
    groupId?: Prisma.SortOrder
    artistId?: Prisma.SortOrder
    fmUsername?: Prisma.SortOrder
    playCount?: Prisma.SortOrder
    switchedTimes?: Prisma.SortOrder
    createdAt?: Prisma.SortOrder
    updatedAt?: Prisma.SortOrder
}

export type CrownAvgOrderByAggregateInput = {
    id?: Prisma.SortOrder
    playCount?: Prisma.SortOrder
    switchedTimes?: Prisma.SortOrder
}

export type CrownMaxOrderByAggregateInput = {
    id?: Prisma.SortOrder
    groupId?: Prisma.SortOrder
    artistId?: Prisma.SortOrder
    fmUsername?: Prisma.SortOrder
    playCount?: Prisma.SortOrder
    switchedTimes?: Prisma.SortOrder
    createdAt?: Prisma.SortOrder
    updatedAt?: Prisma.SortOrder
}

export type CrownMinOrderByAggregateInput = {
    id?: Prisma.SortOrder
    groupId?: Prisma.SortOrder
    artistId?: Prisma.SortOrder
    fmUsername?: Prisma.SortOrder
    playCount?: Prisma.SortOrder
    switchedTimes?: Prisma.SortOrder
    createdAt?: Prisma.SortOrder
    updatedAt?: Prisma.SortOrder
}

export type CrownSumOrderByAggregateInput = {
    id?: Prisma.SortOrder
    playCount?: Prisma.SortOrder
    switchedTimes?: Prisma.SortOrder
}

export type CrownCreateNestedManyWithoutArtistInput = {
    create?: Prisma.XOR<Prisma.CrownCreateWithoutArtistInput, Prisma.CrownUncheckedCreateWithoutArtistInput> | Prisma.CrownCreateWithoutArtistInput[] | Prisma.CrownUncheckedCreateWithoutArtistInput[]
    connectOrCreate?: Prisma.CrownCreateOrConnectWithoutArtistInput | Prisma.CrownCreateOrConnectWithoutArtistInput[]
    createMany?: Prisma.CrownCreateManyArtistInputEnvelope
    connect?: Prisma.CrownWhereUniqueInput | Prisma.CrownWhereUniqueInput[]
}

export type CrownUncheckedCreateNestedManyWithoutArtistInput = {
    create?: Prisma.XOR<Prisma.CrownCreateWithoutArtistInput, Prisma.CrownUncheckedCreateWithoutArtistInput> | Prisma.CrownCreateWithoutArtistInput[] | Prisma.CrownUncheckedCreateWithoutArtistInput[]
    connectOrCreate?: Prisma.CrownCreateOrConnectWithoutArtistInput | Prisma.CrownCreateOrConnectWithoutArtistInput[]
    createMany?: Prisma.CrownCreateManyArtistInputEnvelope
    connect?: Prisma.CrownWhereUniqueInput | Prisma.CrownWhereUniqueInput[]
}

export type CrownUpdateManyWithoutArtistNestedInput = {
    create?: Prisma.XOR<Prisma.CrownCreateWithoutArtistInput, Prisma.CrownUncheckedCreateWithoutArtistInput> | Prisma.CrownCreateWithoutArtistInput[] | Prisma.CrownUncheckedCreateWithoutArtistInput[]
    connectOrCreate?: Prisma.CrownCreateOrConnectWithoutArtistInput | Prisma.CrownCreateOrConnectWithoutArtistInput[]
    upsert?: Prisma.CrownUpsertWithWhereUniqueWithoutArtistInput | Prisma.CrownUpsertWithWhereUniqueWithoutArtistInput[]
    createMany?: Prisma.CrownCreateManyArtistInputEnvelope
    set?: Prisma.CrownWhereUniqueInput | Prisma.CrownWhereUniqueInput[]
    disconnect?: Prisma.CrownWhereUniqueInput | Prisma.CrownWhereUniqueInput[]
    delete?: Prisma.CrownWhereUniqueInput | Prisma.CrownWhereUniqueInput[]
    connect?: Prisma.CrownWhereUniqueInput | Prisma.CrownWhereUniqueInput[]
    update?: Prisma.CrownUpdateWithWhereUniqueWithoutArtistInput | Prisma.CrownUpdateWithWhereUniqueWithoutArtistInput[]
    updateMany?: Prisma.CrownUpdateManyWithWhereWithoutArtistInput | Prisma.CrownUpdateManyWithWhereWithoutArtistInput[]
    deleteMany?: Prisma.CrownScalarWhereInput | Prisma.CrownScalarWhereInput[]
}

export type CrownUncheckedUpdateManyWithoutArtistNestedInput = {
    create?: Prisma.XOR<Prisma.CrownCreateWithoutArtistInput, Prisma.CrownUncheckedCreateWithoutArtistInput> | Prisma.CrownCreateWithoutArtistInput[] | Prisma.CrownUncheckedCreateWithoutArtistInput[]
    connectOrCreate?: Prisma.CrownCreateOrConnectWithoutArtistInput | Prisma.CrownCreateOrConnectWithoutArtistInput[]
    upsert?: Prisma.CrownUpsertWithWhereUniqueWithoutArtistInput | Prisma.CrownUpsertWithWhereUniqueWithoutArtistInput[]
    createMany?: Prisma.CrownCreateManyArtistInputEnvelope
    set?: Prisma.CrownWhereUniqueInput | Prisma.CrownWhereUniqueInput[]
    disconnect?: Prisma.CrownWhereUniqueInput | Prisma.CrownWhereUniqueInput[]
    delete?: Prisma.CrownWhereUniqueInput | Prisma.CrownWhereUniqueInput[]
    connect?: Prisma.CrownWhereUniqueInput | Prisma.CrownWhereUniqueInput[]
    update?: Prisma.CrownUpdateWithWhereUniqueWithoutArtistInput | Prisma.CrownUpdateWithWhereUniqueWithoutArtistInput[]
    updateMany?: Prisma.CrownUpdateManyWithWhereWithoutArtistInput | Prisma.CrownUpdateManyWithWhereWithoutArtistInput[]
    deleteMany?: Prisma.CrownScalarWhereInput | Prisma.CrownScalarWhereInput[]
}

export type CrownCreateWithoutArtistInput = {
    groupId: string
    fmUsername: string
    playCount: number
    switchedTimes?: number
    createdAt?: Date | string
    updatedAt?: Date | string
}

export type CrownUncheckedCreateWithoutArtistInput = {
    id?: number
    groupId: string
    fmUsername: string
    playCount: number
    switchedTimes?: number
    createdAt?: Date | string
    updatedAt?: Date | string
}

export type CrownCreateOrConnectWithoutArtistInput = {
    where: Prisma.CrownWhereUniqueInput
    create: Prisma.XOR<Prisma.CrownCreateWithoutArtistInput, Prisma.CrownUncheckedCreateWithoutArtistInput>
}

export type CrownCreateManyArtistInputEnvelope = {
    data: Prisma.CrownCreateManyArtistInput | Prisma.CrownCreateManyArtistInput[]
    skipDuplicates?: boolean
}

export type CrownUpsertWithWhereUniqueWithoutArtistInput = {
    where: Prisma.CrownWhereUniqueInput
    update: Prisma.XOR<Prisma.CrownUpdateWithoutArtistInput, Prisma.CrownUncheckedUpdateWithoutArtistInput>
    create: Prisma.XOR<Prisma.CrownCreateWithoutArtistInput, Prisma.CrownUncheckedCreateWithoutArtistInput>
}

export type CrownUpdateWithWhereUniqueWithoutArtistInput = {
    where: Prisma.CrownWhereUniqueInput
    data: Prisma.XOR<Prisma.CrownUpdateWithoutArtistInput, Prisma.CrownUncheckedUpdateWithoutArtistInput>
}

export type CrownUpdateManyWithWhereWithoutArtistInput = {
    where: Prisma.CrownScalarWhereInput
    data: Prisma.XOR<Prisma.CrownUpdateManyMutationInput, Prisma.CrownUncheckedUpdateManyWithoutArtistInput>
}

export type CrownScalarWhereInput = {
    AND?: Prisma.CrownScalarWhereInput | Prisma.CrownScalarWhereInput[]
    OR?: Prisma.CrownScalarWhereInput[]
    NOT?: Prisma.CrownScalarWhereInput | Prisma.CrownScalarWhereInput[]
    id?: Prisma.IntFilter<"Crown"> | number
    groupId?: Prisma.StringFilter<"Crown"> | string
    artistId?: Prisma.StringFilter<"Crown"> | string
    fmUsername?: Prisma.StringFilter<"Crown"> | string
    playCount?: Prisma.IntFilter<"Crown"> | number
    switchedTimes?: Prisma.IntFilter<"Crown"> | number
    createdAt?: Prisma.DateTimeFilter<"Crown"> | Date | string
    updatedAt?: Prisma.DateTimeFilter<"Crown"> | Date | string
}

export type CrownCreateManyArtistInput = {
    id?: number
    groupId: string
    fmUsername: string
    playCount: number
    switchedTimes?: number
    createdAt?: Date | string
    updatedAt?: Date | string
}

export type CrownUpdateWithoutArtistInput = {
    groupId?: Prisma.StringFieldUpdateOperationsInput | string
    fmUsername?: Prisma.StringFieldUpdateOperationsInput | string
    playCount?: Prisma.IntFieldUpdateOperationsInput | number
    switchedTimes?: Prisma.IntFieldUpdateOperationsInput | number
    createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
    updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type CrownUncheckedUpdateWithoutArtistInput = {
    id?: Prisma.IntFieldUpdateOperationsInput | number
    groupId?: Prisma.StringFieldUpdateOperationsInput | string
    fmUsername?: Prisma.StringFieldUpdateOperationsInput | string
    playCount?: Prisma.IntFieldUpdateOperationsInput | number
    switchedTimes?: Prisma.IntFieldUpdateOperationsInput | number
    createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
    updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type CrownUncheckedUpdateManyWithoutArtistInput = {
    id?: Prisma.IntFieldUpdateOperationsInput | number
    groupId?: Prisma.StringFieldUpdateOperationsInput | string
    fmUsername?: Prisma.StringFieldUpdateOperationsInput | string
    playCount?: Prisma.IntFieldUpdateOperationsInput | number
    switchedTimes?: Prisma.IntFieldUpdateOperationsInput | number
    createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
    updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}


export type CrownSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
    id?: boolean
    groupId?: boolean
    artistId?: boolean
    fmUsername?: boolean
    playCount?: boolean
    switchedTimes?: boolean
    createdAt?: boolean
    updatedAt?: boolean
    artist?: boolean | Prisma.ArtistDefaultArgs<ExtArgs>
}, ExtArgs["result"]["crown"]>

export type CrownSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
    id?: boolean
    groupId?: boolean
    artistId?: boolean
    fmUsername?: boolean
    playCount?: boolean
    switchedTimes?: boolean
    createdAt?: boolean
    updatedAt?: boolean
    artist?: boolean | Prisma.ArtistDefaultArgs<ExtArgs>
}, ExtArgs["result"]["crown"]>

export type CrownSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
    id?: boolean
    groupId?: boolean
    artistId?: boolean
    fmUsername?: boolean
    playCount?: boolean
    switchedTimes?: boolean
    createdAt?: boolean
    updatedAt?: boolean
    artist?: boolean | Prisma.ArtistDefaultArgs<ExtArgs>
}, ExtArgs["result"]["crown"]>

export type CrownSelectScalar = {
    id?: boolean
    groupId?: boolean
    artistId?: boolean
    fmUsername?: boolean
    playCount?: boolean
    switchedTimes?: boolean
    createdAt?: boolean
    updatedAt?: boolean
}

export type CrownOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "groupId" | "artistId" | "fmUsername" | "playCount" | "switchedTimes" | "createdAt" | "updatedAt", ExtArgs["result"]["crown"]>
export type CrownInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
    artist?: boolean | Prisma.ArtistDefaultArgs<ExtArgs>
}
export type CrownIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
    artist?: boolean | Prisma.ArtistDefaultArgs<ExtArgs>
}
export type CrownIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
    artist?: boolean | Prisma.ArtistDefaultArgs<ExtArgs>
}

export type $CrownPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
    name: "Crown"
    objects: {
        artist: Prisma.$ArtistPayload<ExtArgs>
    }
    scalars: runtime.Types.Extensions.GetPayloadResult<{
        id: number
        groupId: string
        artistId: string
        fmUsername: string
        playCount: number
        switchedTimes: number
        createdAt: Date
        updatedAt: Date
    }, ExtArgs["result"]["crown"]>
    composites: {}
}

export type CrownGetPayload<S extends boolean | null | undefined | CrownDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$CrownPayload, S>

export type CrownCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
    Omit<CrownFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: CrownCountAggregateInputType | true
}

export interface CrownDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
    /**
     * Fields of the Crown model
     */
    readonly fields: CrownFieldRefs;

    [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Crown'], meta: { name: 'Crown' } }

    /**
     * Find zero or one Crown that matches the filter.
     * @param {CrownFindUniqueArgs} args - Arguments to find a Crown
     * @example
     * // Get one Crown
     * const crown = await prisma.crown.findUnique({
     *   where: {
     *     // ... provide filter here
     *   }
     * })
     */
    findUnique<T extends CrownFindUniqueArgs>(args: Prisma.SelectSubset<T, CrownFindUniqueArgs<ExtArgs>>): Prisma.Prisma__CrownClient<runtime.Types.Result.GetResult<Prisma.$CrownPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

    /**
     * Find one Crown that matches the filter or throw an error with `error.code='P2025'`
     * if no matches were found.
     * @param {CrownFindUniqueOrThrowArgs} args - Arguments to find a Crown
     * @example
     * // Get one Crown
     * const crown = await prisma.crown.findUniqueOrThrow({
     *   where: {
     *     // ... provide filter here
     *   }
     * })
     */
    findUniqueOrThrow<T extends CrownFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, CrownFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__CrownClient<runtime.Types.Result.GetResult<Prisma.$CrownPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

    /**
     * Find the first Crown that matches the filter.
     * Note, that providing `undefined` is treated as the value not being there.
     * Read more here: https://pris.ly/d/null-undefined
     * @param {CrownFindFirstArgs} args - Arguments to find a Crown
     * @example
     * // Get one Crown
     * const crown = await prisma.crown.findFirst({
     *   where: {
     *     // ... provide filter here
     *   }
     * })
     */
    findFirst<T extends CrownFindFirstArgs>(args?: Prisma.SelectSubset<T, CrownFindFirstArgs<ExtArgs>>): Prisma.Prisma__CrownClient<runtime.Types.Result.GetResult<Prisma.$CrownPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

    /**
     * Find the first Crown that matches the filter or
     * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
     * Note, that providing `undefined` is treated as the value not being there.
     * Read more here: https://pris.ly/d/null-undefined
     * @param {CrownFindFirstOrThrowArgs} args - Arguments to find a Crown
     * @example
     * // Get one Crown
     * const crown = await prisma.crown.findFirstOrThrow({
     *   where: {
     *     // ... provide filter here
     *   }
     * })
     */
    findFirstOrThrow<T extends CrownFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, CrownFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__CrownClient<runtime.Types.Result.GetResult<Prisma.$CrownPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

    /**
     * Find zero or more Crowns that matches the filter.
     * Note, that providing `undefined` is treated as the value not being there.
     * Read more here: https://pris.ly/d/null-undefined
     * @param {CrownFindManyArgs} args - Arguments to filter and select certain fields only.
     * @example
     * // Get all Crowns
     * const crowns = await prisma.crown.findMany()
     *
     * // Get first 10 Crowns
     * const crowns = await prisma.crown.findMany({ take: 10 })
     *
     * // Only select the `id`
     * const crownWithIdOnly = await prisma.crown.findMany({ select: { id: true } })
     *
     */
    findMany<T extends CrownFindManyArgs>(args?: Prisma.SelectSubset<T, CrownFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$CrownPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

    /**
     * Create a Crown.
     * @param {CrownCreateArgs} args - Arguments to create a Crown.
     * @example
     * // Create one Crown
     * const Crown = await prisma.crown.create({
     *   data: {
     *     // ... data to create a Crown
     *   }
     * })
     *
     */
    create<T extends CrownCreateArgs>(args: Prisma.SelectSubset<T, CrownCreateArgs<ExtArgs>>): Prisma.Prisma__CrownClient<runtime.Types.Result.GetResult<Prisma.$CrownPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

    /**
     * Create many Crowns.
     * @param {CrownCreateManyArgs} args - Arguments to create many Crowns.
     * @example
     * // Create many Crowns
     * const crown = await prisma.crown.createMany({
     *   data: [
     *     // ... provide data here
     *   ]
     * })
     *
     */
    createMany<T extends CrownCreateManyArgs>(args?: Prisma.SelectSubset<T, CrownCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

    /**
     * Create many Crowns and returns the data saved in the database.
     * @param {CrownCreateManyAndReturnArgs} args - Arguments to create many Crowns.
     * @example
     * // Create many Crowns
     * const crown = await prisma.crown.createManyAndReturn({
     *   data: [
     *     // ... provide data here
     *   ]
     * })
     *
     * // Create many Crowns and only return the `id`
     * const crownWithIdOnly = await prisma.crown.createManyAndReturn({
     *   select: { id: true },
     *   data: [
     *     // ... provide data here
     *   ]
     * })
     * Note, that providing `undefined` is treated as the value not being there.
     * Read more here: https://pris.ly/d/null-undefined
     *
     */
    createManyAndReturn<T extends CrownCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, CrownCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$CrownPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

    /**
     * Delete a Crown.
     * @param {CrownDeleteArgs} args - Arguments to delete one Crown.
     * @example
     * // Delete one Crown
     * const Crown = await prisma.crown.delete({
     *   where: {
     *     // ... filter to delete one Crown
     *   }
     * })
     *
     */
    delete<T extends CrownDeleteArgs>(args: Prisma.SelectSubset<T, CrownDeleteArgs<ExtArgs>>): Prisma.Prisma__CrownClient<runtime.Types.Result.GetResult<Prisma.$CrownPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

    /**
     * Update one Crown.
     * @param {CrownUpdateArgs} args - Arguments to update one Crown.
     * @example
     * // Update one Crown
     * const crown = await prisma.crown.update({
     *   where: {
     *     // ... provide filter here
     *   },
     *   data: {
     *     // ... provide data here
     *   }
     * })
     *
     */
    update<T extends CrownUpdateArgs>(args: Prisma.SelectSubset<T, CrownUpdateArgs<ExtArgs>>): Prisma.Prisma__CrownClient<runtime.Types.Result.GetResult<Prisma.$CrownPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

    /**
     * Delete zero or more Crowns.
     * @param {CrownDeleteManyArgs} args - Arguments to filter Crowns to delete.
     * @example
     * // Delete a few Crowns
     * const { count } = await prisma.crown.deleteMany({
     *   where: {
     *     // ... provide filter here
     *   }
     * })
     *
     */
    deleteMany<T extends CrownDeleteManyArgs>(args?: Prisma.SelectSubset<T, CrownDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

    /**
     * Update zero or more Crowns.
     * Note, that providing `undefined` is treated as the value not being there.
     * Read more here: https://pris.ly/d/null-undefined
     * @param {CrownUpdateManyArgs} args - Arguments to update one or more rows.
     * @example
     * // Update many Crowns
     * const crown = await prisma.crown.updateMany({
     *   where: {
     *     // ... provide filter here
     *   },
     *   data: {
     *     // ... provide data here
     *   }
     * })
     *
     */
    updateMany<T extends CrownUpdateManyArgs>(args: Prisma.SelectSubset<T, CrownUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

    /**
     * Update zero or more Crowns and returns the data updated in the database.
     * @param {CrownUpdateManyAndReturnArgs} args - Arguments to update many Crowns.
     * @example
     * // Update many Crowns
     * const crown = await prisma.crown.updateManyAndReturn({
     *   where: {
     *     // ... provide filter here
     *   },
     *   data: [
     *     // ... provide data here
     *   ]
     * })
     *
     * // Update zero or more Crowns and only return the `id`
     * const crownWithIdOnly = await prisma.crown.updateManyAndReturn({
     *   select: { id: true },
     *   where: {
     *     // ... provide filter here
     *   },
     *   data: [
     *     // ... provide data here
     *   ]
     * })
     * Note, that providing `undefined` is treated as the value not being there.
     * Read more here: https://pris.ly/d/null-undefined
     *
     */
    updateManyAndReturn<T extends CrownUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, CrownUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$CrownPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

    /**
     * Create or update one Crown.
     * @param {CrownUpsertArgs} args - Arguments to update or create a Crown.
     * @example
     * // Update or create a Crown
     * const crown = await prisma.crown.upsert({
     *   create: {
     *     // ... data to create a Crown
     *   },
     *   update: {
     *     // ... in case it already exists, update
     *   },
     *   where: {
     *     // ... the filter for the Crown we want to update
     *   }
     * })
     */
    upsert<T extends CrownUpsertArgs>(args: Prisma.SelectSubset<T, CrownUpsertArgs<ExtArgs>>): Prisma.Prisma__CrownClient<runtime.Types.Result.GetResult<Prisma.$CrownPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

    /**
     * Count the number of Crowns.
     * Note, that providing `undefined` is treated as the value not being there.
     * Read more here: https://pris.ly/d/null-undefined
     * @param {CrownCountArgs} args - Arguments to filter Crowns to count.
     * @example
     * // Count the number of Crowns
     * const count = await prisma.crown.count({
     *   where: {
     *     // ... the filter for the Crowns we want to count
     *   }
     * })
     **/
    count<T extends CrownCountArgs>(
        args?: Prisma.Subset<T, CrownCountArgs>,
    ): Prisma.PrismaPromise<
        T extends runtime.Types.Utils.Record<'select', any>
            ? T['select'] extends true
                ? number
                : Prisma.GetScalarType<T['select'], CrownCountAggregateOutputType>
            : number
    >

    /**
     * Allows you to perform aggregations operations on a Crown.
     * Note, that providing `undefined` is treated as the value not being there.
     * Read more here: https://pris.ly/d/null-undefined
     * @param {CrownAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
     * @example
     * // Ordered by age ascending
     * // Where email contains prisma.io
     * // Limited to the 10 users
     * const aggregations = await prisma.user.aggregate({
     *   _avg: {
     *     age: true,
     *   },
     *   where: {
     *     email: {
     *       contains: "prisma.io",
     *     },
     *   },
     *   orderBy: {
     *     age: "asc",
     *   },
     *   take: 10,
     * })
     **/
    aggregate<T extends CrownAggregateArgs>(args: Prisma.Subset<T, CrownAggregateArgs>): Prisma.PrismaPromise<GetCrownAggregateType<T>>

    /**
     * Group by Crown.
     * Note, that providing `undefined` is treated as the value not being there.
     * Read more here: https://pris.ly/d/null-undefined
     * @param {CrownGroupByArgs} args - Group by arguments.
     * @example
     * // Group by city, order by createdAt, get count
     * const result = await prisma.user.groupBy({
     *   by: ['city', 'createdAt'],
     *   orderBy: {
     *     createdAt: true
     *   },
     *   _count: {
     *     _all: true
     *   },
     * })
     *
     **/
    groupBy<
        T extends CrownGroupByArgs,
        HasSelectOrTake extends Prisma.Or<
            Prisma.Extends<'skip', Prisma.Keys<T>>,
            Prisma.Extends<'take', Prisma.Keys<T>>
        >,
        OrderByArg extends Prisma.True extends HasSelectOrTake
            ? { orderBy: CrownGroupByArgs['orderBy'] }
            : { orderBy?: CrownGroupByArgs['orderBy'] },
        OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
        ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
        ByValid extends Prisma.Has<ByFields, OrderFields>,
        HavingFields extends Prisma.GetHavingFields<T['having']>,
        HavingValid extends Prisma.Has<ByFields, HavingFields>,
        ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
        InputErrors extends ByEmpty extends Prisma.True
            ? `Error: "by" must not be empty.`
            : HavingValid extends Prisma.False
                ? {
                    [P in HavingFields]: P extends ByFields
                        ? never
                        : P extends string
                            ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
                            : [
                                Error,
                                'Field ',
                                P,
                                ` in "having" needs to be provided in "by"`,
                            ]
                }[HavingFields]
                : 'take' extends Prisma.Keys<T>
                    ? 'orderBy' extends Prisma.Keys<T>
                        ? ByValid extends Prisma.True
                            ? {}
                            : {
                                [P in OrderFields]: P extends ByFields
                                    ? never
                                    : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
                            }[OrderFields]
                        : 'Error: If you provide "take", you also need to provide "orderBy"'
                    : 'skip' extends Prisma.Keys<T>
                        ? 'orderBy' extends Prisma.Keys<T>
                            ? ByValid extends Prisma.True
                                ? {}
                                : {
                                    [P in OrderFields]: P extends ByFields
                                        ? never
                                        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
                                }[OrderFields]
                            : 'Error: If you provide "skip", you also need to provide "orderBy"'
                        : ByValid extends Prisma.True
                            ? {}
                            : {
                                [P in OrderFields]: P extends ByFields
                                    ? never
                                    : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
                            }[OrderFields]
    >(args: Prisma.SubsetIntersection<T, CrownGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetCrownGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
}

/**
 * The delegate class that acts as a "Promise-like" for Crown.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__CrownClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
    readonly [Symbol.toStringTag]: "PrismaPromise"

    artist<T extends Prisma.ArtistDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.ArtistDefaultArgs<ExtArgs>>): Prisma.Prisma__ArtistClient<runtime.Types.Result.GetResult<Prisma.$ArtistPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>

    /**
     * Attaches callbacks for the resolution and/or rejection of the Promise.
     * @param onfulfilled The callback to execute when the Promise is resolved.
     * @param onrejected The callback to execute when the Promise is rejected.
     * @returns A Promise for the completion of which ever callback is executed.
     */
    then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>

    /**
     * Attaches a callback for only the rejection of the Promise.
     * @param onrejected The callback to execute when the Promise is rejected.
     * @returns A Promise for the completion of the callback.
     */
    catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>

    /**
     * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
     * resolved value cannot be modified from the callback.
     * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
     * @returns A Promise for the completion of the callback.
     */
    finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}


/**
 * Fields of the Crown model
 */
export interface CrownFieldRefs {
    readonly id: Prisma.FieldRef<"Crown", 'Int'>
    readonly groupId: Prisma.FieldRef<"Crown", 'String'>
    readonly artistId: Prisma.FieldRef<"Crown", 'String'>
    readonly fmUsername: Prisma.FieldRef<"Crown", 'String'>
    readonly playCount: Prisma.FieldRef<"Crown", 'Int'>
    readonly switchedTimes: Prisma.FieldRef<"Crown", 'Int'>
    readonly createdAt: Prisma.FieldRef<"Crown", 'DateTime'>
    readonly updatedAt: Prisma.FieldRef<"Crown", 'DateTime'>
}


// Custom InputTypes
/**
 * Crown findUnique
 */
export type CrownFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
    /**
     * Select specific fields to fetch from the Crown
     */
    select?: Prisma.CrownSelect<ExtArgs> | null
    /**
     * Omit specific fields from the Crown
     */
    omit?: Prisma.CrownOmit<ExtArgs> | null
    /**
     * Choose, which related nodes to fetch as well
     */
    include?: Prisma.CrownInclude<ExtArgs> | null
    /**
     * Filter, which Crown to fetch.
     */
    where: Prisma.CrownWhereUniqueInput
}

/**
 * Crown findUniqueOrThrow
 */
export type CrownFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
    /**
     * Select specific fields to fetch from the Crown
     */
    select?: Prisma.CrownSelect<ExtArgs> | null
    /**
     * Omit specific fields from the Crown
     */
    omit?: Prisma.CrownOmit<ExtArgs> | null
    /**
     * Choose, which related nodes to fetch as well
     */
    include?: Prisma.CrownInclude<ExtArgs> | null
    /**
     * Filter, which Crown to fetch.
     */
    where: Prisma.CrownWhereUniqueInput
}

/**
 * Crown findFirst
 */
export type CrownFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
    /**
     * Select specific fields to fetch from the Crown
     */
    select?: Prisma.CrownSelect<ExtArgs> | null
    /**
     * Omit specific fields from the Crown
     */
    omit?: Prisma.CrownOmit<ExtArgs> | null
    /**
     * Choose, which related nodes to fetch as well
     */
    include?: Prisma.CrownInclude<ExtArgs> | null
    /**
     * Filter, which Crown to fetch.
     */
    where?: Prisma.CrownWhereInput
    /**
     * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
     *
     * Determine the order of Crowns to fetch.
     */
    orderBy?: Prisma.CrownOrderByWithRelationInput | Prisma.CrownOrderByWithRelationInput[]
    /**
     * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
     *
     * Sets the position for searching for Crowns.
     */
    cursor?: Prisma.CrownWhereUniqueInput
    /**
     * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
     *
     * Take `±n` Crowns from the position of the cursor.
     */
    take?: number
    /**
     * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
     *
     * Skip the first `n` Crowns.
     */
    skip?: number
    /**
     * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
     *
     * Filter by unique combinations of Crowns.
     */
    distinct?: Prisma.CrownScalarFieldEnum | Prisma.CrownScalarFieldEnum[]
}

/**
 * Crown findFirstOrThrow
 */
export type CrownFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
    /**
     * Select specific fields to fetch from the Crown
     */
    select?: Prisma.CrownSelect<ExtArgs> | null
    /**
     * Omit specific fields from the Crown
     */
    omit?: Prisma.CrownOmit<ExtArgs> | null
    /**
     * Choose, which related nodes to fetch as well
     */
    include?: Prisma.CrownInclude<ExtArgs> | null
    /**
     * Filter, which Crown to fetch.
     */
    where?: Prisma.CrownWhereInput
    /**
     * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
     *
     * Determine the order of Crowns to fetch.
     */
    orderBy?: Prisma.CrownOrderByWithRelationInput | Prisma.CrownOrderByWithRelationInput[]
    /**
     * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
     *
     * Sets the position for searching for Crowns.
     */
    cursor?: Prisma.CrownWhereUniqueInput
    /**
     * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
     *
     * Take `±n` Crowns from the position of the cursor.
     */
    take?: number
    /**
     * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
     *
     * Skip the first `n` Crowns.
     */
    skip?: number
    /**
     * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
     *
     * Filter by unique combinations of Crowns.
     */
    distinct?: Prisma.CrownScalarFieldEnum | Prisma.CrownScalarFieldEnum[]
}

/**
 * Crown findMany
 */
export type CrownFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
    /**
     * Select specific fields to fetch from the Crown
     */
    select?: Prisma.CrownSelect<ExtArgs> | null
    /**
     * Omit specific fields from the Crown
     */
    omit?: Prisma.CrownOmit<ExtArgs> | null
    /**
     * Choose, which related nodes to fetch as well
     */
    include?: Prisma.CrownInclude<ExtArgs> | null
    /**
     * Filter, which Crowns to fetch.
     */
    where?: Prisma.CrownWhereInput
    /**
     * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
     *
     * Determine the order of Crowns to fetch.
     */
    orderBy?: Prisma.CrownOrderByWithRelationInput | Prisma.CrownOrderByWithRelationInput[]
    /**
     * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
     *
     * Sets the position for listing Crowns.
     */
    cursor?: Prisma.CrownWhereUniqueInput
    /**
     * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
     *
     * Take `±n` Crowns from the position of the cursor.
     */
    take?: number
    /**
     * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
     *
     * Skip the first `n` Crowns.
     */
    skip?: number
    distinct?: Prisma.CrownScalarFieldEnum | Prisma.CrownScalarFieldEnum[]
}

/**
 * Crown create
 */
export type CrownCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
    /**
     * Select specific fields to fetch from the Crown
     */
    select?: Prisma.CrownSelect<ExtArgs> | null
    /**
     * Omit specific fields from the Crown
     */
    omit?: Prisma.CrownOmit<ExtArgs> | null
    /**
     * Choose, which related nodes to fetch as well
     */
    include?: Prisma.CrownInclude<ExtArgs> | null
    /**
     * The data needed to create a Crown.
     */
    data: Prisma.XOR<Prisma.CrownCreateInput, Prisma.CrownUncheckedCreateInput>
}

/**
 * Crown createMany
 */
export type CrownCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
    /**
     * The data used to create many Crowns.
     */
    data: Prisma.CrownCreateManyInput | Prisma.CrownCreateManyInput[]
    skipDuplicates?: boolean
}

/**
 * Crown createManyAndReturn
 */
export type CrownCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
    /**
     * Select specific fields to fetch from the Crown
     */
    select?: Prisma.CrownSelectCreateManyAndReturn<ExtArgs> | null
    /**
     * Omit specific fields from the Crown
     */
    omit?: Prisma.CrownOmit<ExtArgs> | null
    /**
     * The data used to create many Crowns.
     */
    data: Prisma.CrownCreateManyInput | Prisma.CrownCreateManyInput[]
    skipDuplicates?: boolean
    /**
     * Choose, which related nodes to fetch as well
     */
    include?: Prisma.CrownIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * Crown update
 */
export type CrownUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
    /**
     * Select specific fields to fetch from the Crown
     */
    select?: Prisma.CrownSelect<ExtArgs> | null
    /**
     * Omit specific fields from the Crown
     */
    omit?: Prisma.CrownOmit<ExtArgs> | null
    /**
     * Choose, which related nodes to fetch as well
     */
    include?: Prisma.CrownInclude<ExtArgs> | null
    /**
     * The data needed to update a Crown.
     */
    data: Prisma.XOR<Prisma.CrownUpdateInput, Prisma.CrownUncheckedUpdateInput>
    /**
     * Choose, which Crown to update.
     */
    where: Prisma.CrownWhereUniqueInput
}

/**
 * Crown updateMany
 */
export type CrownUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
    /**
     * The data used to update Crowns.
     */
    data: Prisma.XOR<Prisma.CrownUpdateManyMutationInput, Prisma.CrownUncheckedUpdateManyInput>
    /**
     * Filter which Crowns to update
     */
    where?: Prisma.CrownWhereInput
    /**
     * Limit how many Crowns to update.
     */
    limit?: number
}

/**
 * Crown updateManyAndReturn
 */
export type CrownUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
    /**
     * Select specific fields to fetch from the Crown
     */
    select?: Prisma.CrownSelectUpdateManyAndReturn<ExtArgs> | null
    /**
     * Omit specific fields from the Crown
     */
    omit?: Prisma.CrownOmit<ExtArgs> | null
    /**
     * The data used to update Crowns.
     */
    data: Prisma.XOR<Prisma.CrownUpdateManyMutationInput, Prisma.CrownUncheckedUpdateManyInput>
    /**
     * Filter which Crowns to update
     */
    where?: Prisma.CrownWhereInput
    /**
     * Limit how many Crowns to update.
     */
    limit?: number
    /**
     * Choose, which related nodes to fetch as well
     */
    include?: Prisma.CrownIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * Crown upsert
 */
export type CrownUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
    /**
     * Select specific fields to fetch from the Crown
     */
    select?: Prisma.CrownSelect<ExtArgs> | null
    /**
     * Omit specific fields from the Crown
     */
    omit?: Prisma.CrownOmit<ExtArgs> | null
    /**
     * Choose, which related nodes to fetch as well
     */
    include?: Prisma.CrownInclude<ExtArgs> | null
    /**
     * The filter to search for the Crown to update in case it exists.
     */
    where: Prisma.CrownWhereUniqueInput
    /**
     * In case the Crown found by the `where` argument doesn't exist, create a new Crown with this data.
     */
    create: Prisma.XOR<Prisma.CrownCreateInput, Prisma.CrownUncheckedCreateInput>
    /**
     * In case the Crown was found with the provided `where` argument, update it with this data.
     */
    update: Prisma.XOR<Prisma.CrownUpdateInput, Prisma.CrownUncheckedUpdateInput>
}

/**
 * Crown delete
 */
export type CrownDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
    /**
     * Select specific fields to fetch from the Crown
     */
    select?: Prisma.CrownSelect<ExtArgs> | null
    /**
     * Omit specific fields from the Crown
     */
    omit?: Prisma.CrownOmit<ExtArgs> | null
    /**
     * Choose, which related nodes to fetch as well
     */
    include?: Prisma.CrownInclude<ExtArgs> | null
    /**
     * Filter which Crown to delete.
     */
    where: Prisma.CrownWhereUniqueInput
}

/**
 * Crown deleteMany
 */
export type CrownDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
    /**
     * Filter which Crowns to delete
     */
    where?: Prisma.CrownWhereInput
    /**
     * Limit how many Crowns to delete.
     */
    limit?: number
}

/**
 * Crown without action
 */
export type CrownDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
    /**
     * Select specific fields to fetch from the Crown
     */
    select?: Prisma.CrownSelect<ExtArgs> | null
    /**
     * Omit specific fields from the Crown
     */
    omit?: Prisma.CrownOmit<ExtArgs> | null
    /**
     * Choose, which related nodes to fetch as well
     */
    include?: Prisma.CrownInclude<ExtArgs> | null
}
