
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `EntityScrobble` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model EntityScrobble
 * 
 */
export type EntityScrobbleModel = runtime.Types.Result.DefaultSelection<Prisma.$EntityScrobblePayload>

export type AggregateEntityScrobble = {
  _count: EntityScrobbleCountAggregateOutputType | null
  _avg: EntityScrobbleAvgAggregateOutputType | null
  _sum: EntityScrobbleSumAggregateOutputType | null
  _min: EntityScrobbleMinAggregateOutputType | null
  _max: EntityScrobbleMaxAggregateOutputType | null
}

export type EntityScrobbleAvgAggregateOutputType = {
  id: number | null
  entityId: number | null
  playCount: number | null
}

export type EntityScrobbleSumAggregateOutputType = {
  id: number | null
  entityId: number | null
  playCount: number | null
}

export type EntityScrobbleMinAggregateOutputType = {
  id: number | null
  entityId: number | null
  fmUsername: string | null
  playCount: number | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type EntityScrobbleMaxAggregateOutputType = {
  id: number | null
  entityId: number | null
  fmUsername: string | null
  playCount: number | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type EntityScrobbleCountAggregateOutputType = {
  id: number
  entityId: number
  fmUsername: number
  playCount: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type EntityScrobbleAvgAggregateInputType = {
  id?: true
  entityId?: true
  playCount?: true
}

export type EntityScrobbleSumAggregateInputType = {
  id?: true
  entityId?: true
  playCount?: true
}

export type EntityScrobbleMinAggregateInputType = {
  id?: true
  entityId?: true
  fmUsername?: true
  playCount?: true
  createdAt?: true
  updatedAt?: true
}

export type EntityScrobbleMaxAggregateInputType = {
  id?: true
  entityId?: true
  fmUsername?: true
  playCount?: true
  createdAt?: true
  updatedAt?: true
}

export type EntityScrobbleCountAggregateInputType = {
  id?: true
  entityId?: true
  fmUsername?: true
  playCount?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type EntityScrobbleAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which EntityScrobble to aggregate.
   */
  where?: Prisma.EntityScrobbleWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of EntityScrobbles to fetch.
   */
  orderBy?: Prisma.EntityScrobbleOrderByWithRelationInput | Prisma.EntityScrobbleOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.EntityScrobbleWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` EntityScrobbles from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` EntityScrobbles.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned EntityScrobbles
  **/
  _count?: true | EntityScrobbleCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: EntityScrobbleAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: EntityScrobbleSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: EntityScrobbleMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: EntityScrobbleMaxAggregateInputType
}

export type GetEntityScrobbleAggregateType<T extends EntityScrobbleAggregateArgs> = {
      [P in keyof T & keyof AggregateEntityScrobble]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateEntityScrobble[P]>
    : Prisma.GetScalarType<T[P], AggregateEntityScrobble[P]>
}




export type EntityScrobbleGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.EntityScrobbleWhereInput
  orderBy?: Prisma.EntityScrobbleOrderByWithAggregationInput | Prisma.EntityScrobbleOrderByWithAggregationInput[]
  by: Prisma.EntityScrobbleScalarFieldEnum[] | Prisma.EntityScrobbleScalarFieldEnum
  having?: Prisma.EntityScrobbleScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: EntityScrobbleCountAggregateInputType | true
  _avg?: EntityScrobbleAvgAggregateInputType
  _sum?: EntityScrobbleSumAggregateInputType
  _min?: EntityScrobbleMinAggregateInputType
  _max?: EntityScrobbleMaxAggregateInputType
}

export type EntityScrobbleGroupByOutputType = {
  id: number
  entityId: number
  fmUsername: string
  playCount: number
  createdAt: Date
  updatedAt: Date
  _count: EntityScrobbleCountAggregateOutputType | null
  _avg: EntityScrobbleAvgAggregateOutputType | null
  _sum: EntityScrobbleSumAggregateOutputType | null
  _min: EntityScrobbleMinAggregateOutputType | null
  _max: EntityScrobbleMaxAggregateOutputType | null
}

export type GetEntityScrobbleGroupByPayload<T extends EntityScrobbleGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<EntityScrobbleGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof EntityScrobbleGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], EntityScrobbleGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], EntityScrobbleGroupByOutputType[P]>
      }
    >
  >



export type EntityScrobbleWhereInput = {
  AND?: Prisma.EntityScrobbleWhereInput | Prisma.EntityScrobbleWhereInput[]
  OR?: Prisma.EntityScrobbleWhereInput[]
  NOT?: Prisma.EntityScrobbleWhereInput | Prisma.EntityScrobbleWhereInput[]
  id?: Prisma.IntFilter<"EntityScrobble"> | number
  entityId?: Prisma.IntFilter<"EntityScrobble"> | number
  fmUsername?: Prisma.StringFilter<"EntityScrobble"> | string
  playCount?: Prisma.IntFilter<"EntityScrobble"> | number
  createdAt?: Prisma.DateTimeFilter<"EntityScrobble"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"EntityScrobble"> | Date | string
  lastFmUser?: Prisma.XOR<Prisma.LastFmUserScalarRelationFilter, Prisma.LastFmUserWhereInput>
  entity?: Prisma.XOR<Prisma.EntityScalarRelationFilter, Prisma.EntityWhereInput>
}

export type EntityScrobbleOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  entityId?: Prisma.SortOrder
  fmUsername?: Prisma.SortOrder
  playCount?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  lastFmUser?: Prisma.LastFmUserOrderByWithRelationInput
  entity?: Prisma.EntityOrderByWithRelationInput
}

export type EntityScrobbleWhereUniqueInput = Prisma.AtLeast<{
  id?: number
  fmUsername_entityId?: Prisma.EntityScrobbleFmUsernameEntityIdCompoundUniqueInput
  AND?: Prisma.EntityScrobbleWhereInput | Prisma.EntityScrobbleWhereInput[]
  OR?: Prisma.EntityScrobbleWhereInput[]
  NOT?: Prisma.EntityScrobbleWhereInput | Prisma.EntityScrobbleWhereInput[]
  entityId?: Prisma.IntFilter<"EntityScrobble"> | number
  fmUsername?: Prisma.StringFilter<"EntityScrobble"> | string
  playCount?: Prisma.IntFilter<"EntityScrobble"> | number
  createdAt?: Prisma.DateTimeFilter<"EntityScrobble"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"EntityScrobble"> | Date | string
  lastFmUser?: Prisma.XOR<Prisma.LastFmUserScalarRelationFilter, Prisma.LastFmUserWhereInput>
  entity?: Prisma.XOR<Prisma.EntityScalarRelationFilter, Prisma.EntityWhereInput>
}, "id" | "fmUsername_entityId">

export type EntityScrobbleOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  entityId?: Prisma.SortOrder
  fmUsername?: Prisma.SortOrder
  playCount?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.EntityScrobbleCountOrderByAggregateInput
  _avg?: Prisma.EntityScrobbleAvgOrderByAggregateInput
  _max?: Prisma.EntityScrobbleMaxOrderByAggregateInput
  _min?: Prisma.EntityScrobbleMinOrderByAggregateInput
  _sum?: Prisma.EntityScrobbleSumOrderByAggregateInput
}

export type EntityScrobbleScalarWhereWithAggregatesInput = {
  AND?: Prisma.EntityScrobbleScalarWhereWithAggregatesInput | Prisma.EntityScrobbleScalarWhereWithAggregatesInput[]
  OR?: Prisma.EntityScrobbleScalarWhereWithAggregatesInput[]
  NOT?: Prisma.EntityScrobbleScalarWhereWithAggregatesInput | Prisma.EntityScrobbleScalarWhereWithAggregatesInput[]
  id?: Prisma.IntWithAggregatesFilter<"EntityScrobble"> | number
  entityId?: Prisma.IntWithAggregatesFilter<"EntityScrobble"> | number
  fmUsername?: Prisma.StringWithAggregatesFilter<"EntityScrobble"> | string
  playCount?: Prisma.IntWithAggregatesFilter<"EntityScrobble"> | number
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"EntityScrobble"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"EntityScrobble"> | Date | string
}

export type EntityScrobbleCreateInput = {
  playCount: number
  createdAt?: Date | string
  updatedAt?: Date | string
  lastFmUser: Prisma.LastFmUserCreateNestedOneWithoutEntityScrobblesInput
  entity: Prisma.EntityCreateNestedOneWithoutEntityScrobblesInput
}

export type EntityScrobbleUncheckedCreateInput = {
  id?: number
  entityId: number
  fmUsername: string
  playCount: number
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type EntityScrobbleUpdateInput = {
  playCount?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  lastFmUser?: Prisma.LastFmUserUpdateOneRequiredWithoutEntityScrobblesNestedInput
  entity?: Prisma.EntityUpdateOneRequiredWithoutEntityScrobblesNestedInput
}

export type EntityScrobbleUncheckedUpdateInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  entityId?: Prisma.IntFieldUpdateOperationsInput | number
  fmUsername?: Prisma.StringFieldUpdateOperationsInput | string
  playCount?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type EntityScrobbleCreateManyInput = {
  id?: number
  entityId: number
  fmUsername: string
  playCount: number
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type EntityScrobbleUpdateManyMutationInput = {
  playCount?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type EntityScrobbleUncheckedUpdateManyInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  entityId?: Prisma.IntFieldUpdateOperationsInput | number
  fmUsername?: Prisma.StringFieldUpdateOperationsInput | string
  playCount?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type EntityScrobbleListRelationFilter = {
  every?: Prisma.EntityScrobbleWhereInput
  some?: Prisma.EntityScrobbleWhereInput
  none?: Prisma.EntityScrobbleWhereInput
}

export type EntityScrobbleOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type EntityScrobbleFmUsernameEntityIdCompoundUniqueInput = {
  fmUsername: string
  entityId: number
}

export type EntityScrobbleCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  entityId?: Prisma.SortOrder
  fmUsername?: Prisma.SortOrder
  playCount?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type EntityScrobbleAvgOrderByAggregateInput = {
  id?: Prisma.SortOrder
  entityId?: Prisma.SortOrder
  playCount?: Prisma.SortOrder
}

export type EntityScrobbleMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  entityId?: Prisma.SortOrder
  fmUsername?: Prisma.SortOrder
  playCount?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type EntityScrobbleMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  entityId?: Prisma.SortOrder
  fmUsername?: Prisma.SortOrder
  playCount?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type EntityScrobbleSumOrderByAggregateInput = {
  id?: Prisma.SortOrder
  entityId?: Prisma.SortOrder
  playCount?: Prisma.SortOrder
}

export type EntityScrobbleCreateNestedManyWithoutLastFmUserInput = {
  create?: Prisma.XOR<Prisma.EntityScrobbleCreateWithoutLastFmUserInput, Prisma.EntityScrobbleUncheckedCreateWithoutLastFmUserInput> | Prisma.EntityScrobbleCreateWithoutLastFmUserInput[] | Prisma.EntityScrobbleUncheckedCreateWithoutLastFmUserInput[]
  connectOrCreate?: Prisma.EntityScrobbleCreateOrConnectWithoutLastFmUserInput | Prisma.EntityScrobbleCreateOrConnectWithoutLastFmUserInput[]
  createMany?: Prisma.EntityScrobbleCreateManyLastFmUserInputEnvelope
  connect?: Prisma.EntityScrobbleWhereUniqueInput | Prisma.EntityScrobbleWhereUniqueInput[]
}

export type EntityScrobbleUncheckedCreateNestedManyWithoutLastFmUserInput = {
  create?: Prisma.XOR<Prisma.EntityScrobbleCreateWithoutLastFmUserInput, Prisma.EntityScrobbleUncheckedCreateWithoutLastFmUserInput> | Prisma.EntityScrobbleCreateWithoutLastFmUserInput[] | Prisma.EntityScrobbleUncheckedCreateWithoutLastFmUserInput[]
  connectOrCreate?: Prisma.EntityScrobbleCreateOrConnectWithoutLastFmUserInput | Prisma.EntityScrobbleCreateOrConnectWithoutLastFmUserInput[]
  createMany?: Prisma.EntityScrobbleCreateManyLastFmUserInputEnvelope
  connect?: Prisma.EntityScrobbleWhereUniqueInput | Prisma.EntityScrobbleWhereUniqueInput[]
}

export type EntityScrobbleUpdateManyWithoutLastFmUserNestedInput = {
  create?: Prisma.XOR<Prisma.EntityScrobbleCreateWithoutLastFmUserInput, Prisma.EntityScrobbleUncheckedCreateWithoutLastFmUserInput> | Prisma.EntityScrobbleCreateWithoutLastFmUserInput[] | Prisma.EntityScrobbleUncheckedCreateWithoutLastFmUserInput[]
  connectOrCreate?: Prisma.EntityScrobbleCreateOrConnectWithoutLastFmUserInput | Prisma.EntityScrobbleCreateOrConnectWithoutLastFmUserInput[]
  upsert?: Prisma.EntityScrobbleUpsertWithWhereUniqueWithoutLastFmUserInput | Prisma.EntityScrobbleUpsertWithWhereUniqueWithoutLastFmUserInput[]
  createMany?: Prisma.EntityScrobbleCreateManyLastFmUserInputEnvelope
  set?: Prisma.EntityScrobbleWhereUniqueInput | Prisma.EntityScrobbleWhereUniqueInput[]
  disconnect?: Prisma.EntityScrobbleWhereUniqueInput | Prisma.EntityScrobbleWhereUniqueInput[]
  delete?: Prisma.EntityScrobbleWhereUniqueInput | Prisma.EntityScrobbleWhereUniqueInput[]
  connect?: Prisma.EntityScrobbleWhereUniqueInput | Prisma.EntityScrobbleWhereUniqueInput[]
  update?: Prisma.EntityScrobbleUpdateWithWhereUniqueWithoutLastFmUserInput | Prisma.EntityScrobbleUpdateWithWhereUniqueWithoutLastFmUserInput[]
  updateMany?: Prisma.EntityScrobbleUpdateManyWithWhereWithoutLastFmUserInput | Prisma.EntityScrobbleUpdateManyWithWhereWithoutLastFmUserInput[]
  deleteMany?: Prisma.EntityScrobbleScalarWhereInput | Prisma.EntityScrobbleScalarWhereInput[]
}

export type EntityScrobbleUncheckedUpdateManyWithoutLastFmUserNestedInput = {
  create?: Prisma.XOR<Prisma.EntityScrobbleCreateWithoutLastFmUserInput, Prisma.EntityScrobbleUncheckedCreateWithoutLastFmUserInput> | Prisma.EntityScrobbleCreateWithoutLastFmUserInput[] | Prisma.EntityScrobbleUncheckedCreateWithoutLastFmUserInput[]
  connectOrCreate?: Prisma.EntityScrobbleCreateOrConnectWithoutLastFmUserInput | Prisma.EntityScrobbleCreateOrConnectWithoutLastFmUserInput[]
  upsert?: Prisma.EntityScrobbleUpsertWithWhereUniqueWithoutLastFmUserInput | Prisma.EntityScrobbleUpsertWithWhereUniqueWithoutLastFmUserInput[]
  createMany?: Prisma.EntityScrobbleCreateManyLastFmUserInputEnvelope
  set?: Prisma.EntityScrobbleWhereUniqueInput | Prisma.EntityScrobbleWhereUniqueInput[]
  disconnect?: Prisma.EntityScrobbleWhereUniqueInput | Prisma.EntityScrobbleWhereUniqueInput[]
  delete?: Prisma.EntityScrobbleWhereUniqueInput | Prisma.EntityScrobbleWhereUniqueInput[]
  connect?: Prisma.EntityScrobbleWhereUniqueInput | Prisma.EntityScrobbleWhereUniqueInput[]
  update?: Prisma.EntityScrobbleUpdateWithWhereUniqueWithoutLastFmUserInput | Prisma.EntityScrobbleUpdateWithWhereUniqueWithoutLastFmUserInput[]
  updateMany?: Prisma.EntityScrobbleUpdateManyWithWhereWithoutLastFmUserInput | Prisma.EntityScrobbleUpdateManyWithWhereWithoutLastFmUserInput[]
  deleteMany?: Prisma.EntityScrobbleScalarWhereInput | Prisma.EntityScrobbleScalarWhereInput[]
}

export type EntityScrobbleCreateNestedManyWithoutEntityInput = {
  create?: Prisma.XOR<Prisma.EntityScrobbleCreateWithoutEntityInput, Prisma.EntityScrobbleUncheckedCreateWithoutEntityInput> | Prisma.EntityScrobbleCreateWithoutEntityInput[] | Prisma.EntityScrobbleUncheckedCreateWithoutEntityInput[]
  connectOrCreate?: Prisma.EntityScrobbleCreateOrConnectWithoutEntityInput | Prisma.EntityScrobbleCreateOrConnectWithoutEntityInput[]
  createMany?: Prisma.EntityScrobbleCreateManyEntityInputEnvelope
  connect?: Prisma.EntityScrobbleWhereUniqueInput | Prisma.EntityScrobbleWhereUniqueInput[]
}

export type EntityScrobbleUncheckedCreateNestedManyWithoutEntityInput = {
  create?: Prisma.XOR<Prisma.EntityScrobbleCreateWithoutEntityInput, Prisma.EntityScrobbleUncheckedCreateWithoutEntityInput> | Prisma.EntityScrobbleCreateWithoutEntityInput[] | Prisma.EntityScrobbleUncheckedCreateWithoutEntityInput[]
  connectOrCreate?: Prisma.EntityScrobbleCreateOrConnectWithoutEntityInput | Prisma.EntityScrobbleCreateOrConnectWithoutEntityInput[]
  createMany?: Prisma.EntityScrobbleCreateManyEntityInputEnvelope
  connect?: Prisma.EntityScrobbleWhereUniqueInput | Prisma.EntityScrobbleWhereUniqueInput[]
}

export type EntityScrobbleUpdateManyWithoutEntityNestedInput = {
  create?: Prisma.XOR<Prisma.EntityScrobbleCreateWithoutEntityInput, Prisma.EntityScrobbleUncheckedCreateWithoutEntityInput> | Prisma.EntityScrobbleCreateWithoutEntityInput[] | Prisma.EntityScrobbleUncheckedCreateWithoutEntityInput[]
  connectOrCreate?: Prisma.EntityScrobbleCreateOrConnectWithoutEntityInput | Prisma.EntityScrobbleCreateOrConnectWithoutEntityInput[]
  upsert?: Prisma.EntityScrobbleUpsertWithWhereUniqueWithoutEntityInput | Prisma.EntityScrobbleUpsertWithWhereUniqueWithoutEntityInput[]
  createMany?: Prisma.EntityScrobbleCreateManyEntityInputEnvelope
  set?: Prisma.EntityScrobbleWhereUniqueInput | Prisma.EntityScrobbleWhereUniqueInput[]
  disconnect?: Prisma.EntityScrobbleWhereUniqueInput | Prisma.EntityScrobbleWhereUniqueInput[]
  delete?: Prisma.EntityScrobbleWhereUniqueInput | Prisma.EntityScrobbleWhereUniqueInput[]
  connect?: Prisma.EntityScrobbleWhereUniqueInput | Prisma.EntityScrobbleWhereUniqueInput[]
  update?: Prisma.EntityScrobbleUpdateWithWhereUniqueWithoutEntityInput | Prisma.EntityScrobbleUpdateWithWhereUniqueWithoutEntityInput[]
  updateMany?: Prisma.EntityScrobbleUpdateManyWithWhereWithoutEntityInput | Prisma.EntityScrobbleUpdateManyWithWhereWithoutEntityInput[]
  deleteMany?: Prisma.EntityScrobbleScalarWhereInput | Prisma.EntityScrobbleScalarWhereInput[]
}

export type EntityScrobbleUncheckedUpdateManyWithoutEntityNestedInput = {
  create?: Prisma.XOR<Prisma.EntityScrobbleCreateWithoutEntityInput, Prisma.EntityScrobbleUncheckedCreateWithoutEntityInput> | Prisma.EntityScrobbleCreateWithoutEntityInput[] | Prisma.EntityScrobbleUncheckedCreateWithoutEntityInput[]
  connectOrCreate?: Prisma.EntityScrobbleCreateOrConnectWithoutEntityInput | Prisma.EntityScrobbleCreateOrConnectWithoutEntityInput[]
  upsert?: Prisma.EntityScrobbleUpsertWithWhereUniqueWithoutEntityInput | Prisma.EntityScrobbleUpsertWithWhereUniqueWithoutEntityInput[]
  createMany?: Prisma.EntityScrobbleCreateManyEntityInputEnvelope
  set?: Prisma.EntityScrobbleWhereUniqueInput | Prisma.EntityScrobbleWhereUniqueInput[]
  disconnect?: Prisma.EntityScrobbleWhereUniqueInput | Prisma.EntityScrobbleWhereUniqueInput[]
  delete?: Prisma.EntityScrobbleWhereUniqueInput | Prisma.EntityScrobbleWhereUniqueInput[]
  connect?: Prisma.EntityScrobbleWhereUniqueInput | Prisma.EntityScrobbleWhereUniqueInput[]
  update?: Prisma.EntityScrobbleUpdateWithWhereUniqueWithoutEntityInput | Prisma.EntityScrobbleUpdateWithWhereUniqueWithoutEntityInput[]
  updateMany?: Prisma.EntityScrobbleUpdateManyWithWhereWithoutEntityInput | Prisma.EntityScrobbleUpdateManyWithWhereWithoutEntityInput[]
  deleteMany?: Prisma.EntityScrobbleScalarWhereInput | Prisma.EntityScrobbleScalarWhereInput[]
}

export type EntityScrobbleCreateWithoutLastFmUserInput = {
  playCount: number
  createdAt?: Date | string
  updatedAt?: Date | string
  entity: Prisma.EntityCreateNestedOneWithoutEntityScrobblesInput
}

export type EntityScrobbleUncheckedCreateWithoutLastFmUserInput = {
  id?: number
  entityId: number
  playCount: number
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type EntityScrobbleCreateOrConnectWithoutLastFmUserInput = {
  where: Prisma.EntityScrobbleWhereUniqueInput
  create: Prisma.XOR<Prisma.EntityScrobbleCreateWithoutLastFmUserInput, Prisma.EntityScrobbleUncheckedCreateWithoutLastFmUserInput>
}

export type EntityScrobbleCreateManyLastFmUserInputEnvelope = {
  data: Prisma.EntityScrobbleCreateManyLastFmUserInput | Prisma.EntityScrobbleCreateManyLastFmUserInput[]
  skipDuplicates?: boolean
}

export type EntityScrobbleUpsertWithWhereUniqueWithoutLastFmUserInput = {
  where: Prisma.EntityScrobbleWhereUniqueInput
  update: Prisma.XOR<Prisma.EntityScrobbleUpdateWithoutLastFmUserInput, Prisma.EntityScrobbleUncheckedUpdateWithoutLastFmUserInput>
  create: Prisma.XOR<Prisma.EntityScrobbleCreateWithoutLastFmUserInput, Prisma.EntityScrobbleUncheckedCreateWithoutLastFmUserInput>
}

export type EntityScrobbleUpdateWithWhereUniqueWithoutLastFmUserInput = {
  where: Prisma.EntityScrobbleWhereUniqueInput
  data: Prisma.XOR<Prisma.EntityScrobbleUpdateWithoutLastFmUserInput, Prisma.EntityScrobbleUncheckedUpdateWithoutLastFmUserInput>
}

export type EntityScrobbleUpdateManyWithWhereWithoutLastFmUserInput = {
  where: Prisma.EntityScrobbleScalarWhereInput
  data: Prisma.XOR<Prisma.EntityScrobbleUpdateManyMutationInput, Prisma.EntityScrobbleUncheckedUpdateManyWithoutLastFmUserInput>
}

export type EntityScrobbleScalarWhereInput = {
  AND?: Prisma.EntityScrobbleScalarWhereInput | Prisma.EntityScrobbleScalarWhereInput[]
  OR?: Prisma.EntityScrobbleScalarWhereInput[]
  NOT?: Prisma.EntityScrobbleScalarWhereInput | Prisma.EntityScrobbleScalarWhereInput[]
  id?: Prisma.IntFilter<"EntityScrobble"> | number
  entityId?: Prisma.IntFilter<"EntityScrobble"> | number
  fmUsername?: Prisma.StringFilter<"EntityScrobble"> | string
  playCount?: Prisma.IntFilter<"EntityScrobble"> | number
  createdAt?: Prisma.DateTimeFilter<"EntityScrobble"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"EntityScrobble"> | Date | string
}

export type EntityScrobbleCreateWithoutEntityInput = {
  playCount: number
  createdAt?: Date | string
  updatedAt?: Date | string
  lastFmUser: Prisma.LastFmUserCreateNestedOneWithoutEntityScrobblesInput
}

export type EntityScrobbleUncheckedCreateWithoutEntityInput = {
  id?: number
  fmUsername: string
  playCount: number
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type EntityScrobbleCreateOrConnectWithoutEntityInput = {
  where: Prisma.EntityScrobbleWhereUniqueInput
  create: Prisma.XOR<Prisma.EntityScrobbleCreateWithoutEntityInput, Prisma.EntityScrobbleUncheckedCreateWithoutEntityInput>
}

export type EntityScrobbleCreateManyEntityInputEnvelope = {
  data: Prisma.EntityScrobbleCreateManyEntityInput | Prisma.EntityScrobbleCreateManyEntityInput[]
  skipDuplicates?: boolean
}

export type EntityScrobbleUpsertWithWhereUniqueWithoutEntityInput = {
  where: Prisma.EntityScrobbleWhereUniqueInput
  update: Prisma.XOR<Prisma.EntityScrobbleUpdateWithoutEntityInput, Prisma.EntityScrobbleUncheckedUpdateWithoutEntityInput>
  create: Prisma.XOR<Prisma.EntityScrobbleCreateWithoutEntityInput, Prisma.EntityScrobbleUncheckedCreateWithoutEntityInput>
}

export type EntityScrobbleUpdateWithWhereUniqueWithoutEntityInput = {
  where: Prisma.EntityScrobbleWhereUniqueInput
  data: Prisma.XOR<Prisma.EntityScrobbleUpdateWithoutEntityInput, Prisma.EntityScrobbleUncheckedUpdateWithoutEntityInput>
}

export type EntityScrobbleUpdateManyWithWhereWithoutEntityInput = {
  where: Prisma.EntityScrobbleScalarWhereInput
  data: Prisma.XOR<Prisma.EntityScrobbleUpdateManyMutationInput, Prisma.EntityScrobbleUncheckedUpdateManyWithoutEntityInput>
}

export type EntityScrobbleCreateManyLastFmUserInput = {
  id?: number
  entityId: number
  playCount: number
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type EntityScrobbleUpdateWithoutLastFmUserInput = {
  playCount?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  entity?: Prisma.EntityUpdateOneRequiredWithoutEntityScrobblesNestedInput
}

export type EntityScrobbleUncheckedUpdateWithoutLastFmUserInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  entityId?: Prisma.IntFieldUpdateOperationsInput | number
  playCount?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type EntityScrobbleUncheckedUpdateManyWithoutLastFmUserInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  entityId?: Prisma.IntFieldUpdateOperationsInput | number
  playCount?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type EntityScrobbleCreateManyEntityInput = {
  id?: number
  fmUsername: string
  playCount: number
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type EntityScrobbleUpdateWithoutEntityInput = {
  playCount?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  lastFmUser?: Prisma.LastFmUserUpdateOneRequiredWithoutEntityScrobblesNestedInput
}

export type EntityScrobbleUncheckedUpdateWithoutEntityInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  fmUsername?: Prisma.StringFieldUpdateOperationsInput | string
  playCount?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type EntityScrobbleUncheckedUpdateManyWithoutEntityInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  fmUsername?: Prisma.StringFieldUpdateOperationsInput | string
  playCount?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type EntityScrobbleSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  entityId?: boolean
  fmUsername?: boolean
  playCount?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  lastFmUser?: boolean | Prisma.LastFmUserDefaultArgs<ExtArgs>
  entity?: boolean | Prisma.EntityDefaultArgs<ExtArgs>
}, ExtArgs["result"]["entityScrobble"]>

export type EntityScrobbleSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  entityId?: boolean
  fmUsername?: boolean
  playCount?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  lastFmUser?: boolean | Prisma.LastFmUserDefaultArgs<ExtArgs>
  entity?: boolean | Prisma.EntityDefaultArgs<ExtArgs>
}, ExtArgs["result"]["entityScrobble"]>

export type EntityScrobbleSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  entityId?: boolean
  fmUsername?: boolean
  playCount?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  lastFmUser?: boolean | Prisma.LastFmUserDefaultArgs<ExtArgs>
  entity?: boolean | Prisma.EntityDefaultArgs<ExtArgs>
}, ExtArgs["result"]["entityScrobble"]>

export type EntityScrobbleSelectScalar = {
  id?: boolean
  entityId?: boolean
  fmUsername?: boolean
  playCount?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type EntityScrobbleOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "entityId" | "fmUsername" | "playCount" | "createdAt" | "updatedAt", ExtArgs["result"]["entityScrobble"]>
export type EntityScrobbleInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  lastFmUser?: boolean | Prisma.LastFmUserDefaultArgs<ExtArgs>
  entity?: boolean | Prisma.EntityDefaultArgs<ExtArgs>
}
export type EntityScrobbleIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  lastFmUser?: boolean | Prisma.LastFmUserDefaultArgs<ExtArgs>
  entity?: boolean | Prisma.EntityDefaultArgs<ExtArgs>
}
export type EntityScrobbleIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  lastFmUser?: boolean | Prisma.LastFmUserDefaultArgs<ExtArgs>
  entity?: boolean | Prisma.EntityDefaultArgs<ExtArgs>
}

export type $EntityScrobblePayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "EntityScrobble"
  objects: {
    lastFmUser: Prisma.$LastFmUserPayload<ExtArgs>
    entity: Prisma.$EntityPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: number
    entityId: number
    fmUsername: string
    playCount: number
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["entityScrobble"]>
  composites: {}
}

export type EntityScrobbleGetPayload<S extends boolean | null | undefined | EntityScrobbleDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$EntityScrobblePayload, S>

export type EntityScrobbleCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<EntityScrobbleFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: EntityScrobbleCountAggregateInputType | true
  }

export interface EntityScrobbleDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['EntityScrobble'], meta: { name: 'EntityScrobble' } }
  /**
   * Find zero or one EntityScrobble that matches the filter.
   * @param {EntityScrobbleFindUniqueArgs} args - Arguments to find a EntityScrobble
   * @example
   * // Get one EntityScrobble
   * const entityScrobble = await prisma.entityScrobble.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends EntityScrobbleFindUniqueArgs>(args: Prisma.SelectSubset<T, EntityScrobbleFindUniqueArgs<ExtArgs>>): Prisma.Prisma__EntityScrobbleClient<runtime.Types.Result.GetResult<Prisma.$EntityScrobblePayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one EntityScrobble that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {EntityScrobbleFindUniqueOrThrowArgs} args - Arguments to find a EntityScrobble
   * @example
   * // Get one EntityScrobble
   * const entityScrobble = await prisma.entityScrobble.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends EntityScrobbleFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, EntityScrobbleFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__EntityScrobbleClient<runtime.Types.Result.GetResult<Prisma.$EntityScrobblePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first EntityScrobble that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {EntityScrobbleFindFirstArgs} args - Arguments to find a EntityScrobble
   * @example
   * // Get one EntityScrobble
   * const entityScrobble = await prisma.entityScrobble.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends EntityScrobbleFindFirstArgs>(args?: Prisma.SelectSubset<T, EntityScrobbleFindFirstArgs<ExtArgs>>): Prisma.Prisma__EntityScrobbleClient<runtime.Types.Result.GetResult<Prisma.$EntityScrobblePayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first EntityScrobble that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {EntityScrobbleFindFirstOrThrowArgs} args - Arguments to find a EntityScrobble
   * @example
   * // Get one EntityScrobble
   * const entityScrobble = await prisma.entityScrobble.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends EntityScrobbleFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, EntityScrobbleFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__EntityScrobbleClient<runtime.Types.Result.GetResult<Prisma.$EntityScrobblePayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more EntityScrobbles that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {EntityScrobbleFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all EntityScrobbles
   * const entityScrobbles = await prisma.entityScrobble.findMany()
   * 
   * // Get first 10 EntityScrobbles
   * const entityScrobbles = await prisma.entityScrobble.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const entityScrobbleWithIdOnly = await prisma.entityScrobble.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends EntityScrobbleFindManyArgs>(args?: Prisma.SelectSubset<T, EntityScrobbleFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$EntityScrobblePayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a EntityScrobble.
   * @param {EntityScrobbleCreateArgs} args - Arguments to create a EntityScrobble.
   * @example
   * // Create one EntityScrobble
   * const EntityScrobble = await prisma.entityScrobble.create({
   *   data: {
   *     // ... data to create a EntityScrobble
   *   }
   * })
   * 
   */
  create<T extends EntityScrobbleCreateArgs>(args: Prisma.SelectSubset<T, EntityScrobbleCreateArgs<ExtArgs>>): Prisma.Prisma__EntityScrobbleClient<runtime.Types.Result.GetResult<Prisma.$EntityScrobblePayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many EntityScrobbles.
   * @param {EntityScrobbleCreateManyArgs} args - Arguments to create many EntityScrobbles.
   * @example
   * // Create many EntityScrobbles
   * const entityScrobble = await prisma.entityScrobble.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends EntityScrobbleCreateManyArgs>(args?: Prisma.SelectSubset<T, EntityScrobbleCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many EntityScrobbles and returns the data saved in the database.
   * @param {EntityScrobbleCreateManyAndReturnArgs} args - Arguments to create many EntityScrobbles.
   * @example
   * // Create many EntityScrobbles
   * const entityScrobble = await prisma.entityScrobble.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many EntityScrobbles and only return the `id`
   * const entityScrobbleWithIdOnly = await prisma.entityScrobble.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends EntityScrobbleCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, EntityScrobbleCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$EntityScrobblePayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a EntityScrobble.
   * @param {EntityScrobbleDeleteArgs} args - Arguments to delete one EntityScrobble.
   * @example
   * // Delete one EntityScrobble
   * const EntityScrobble = await prisma.entityScrobble.delete({
   *   where: {
   *     // ... filter to delete one EntityScrobble
   *   }
   * })
   * 
   */
  delete<T extends EntityScrobbleDeleteArgs>(args: Prisma.SelectSubset<T, EntityScrobbleDeleteArgs<ExtArgs>>): Prisma.Prisma__EntityScrobbleClient<runtime.Types.Result.GetResult<Prisma.$EntityScrobblePayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one EntityScrobble.
   * @param {EntityScrobbleUpdateArgs} args - Arguments to update one EntityScrobble.
   * @example
   * // Update one EntityScrobble
   * const entityScrobble = await prisma.entityScrobble.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends EntityScrobbleUpdateArgs>(args: Prisma.SelectSubset<T, EntityScrobbleUpdateArgs<ExtArgs>>): Prisma.Prisma__EntityScrobbleClient<runtime.Types.Result.GetResult<Prisma.$EntityScrobblePayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more EntityScrobbles.
   * @param {EntityScrobbleDeleteManyArgs} args - Arguments to filter EntityScrobbles to delete.
   * @example
   * // Delete a few EntityScrobbles
   * const { count } = await prisma.entityScrobble.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends EntityScrobbleDeleteManyArgs>(args?: Prisma.SelectSubset<T, EntityScrobbleDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more EntityScrobbles.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {EntityScrobbleUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many EntityScrobbles
   * const entityScrobble = await prisma.entityScrobble.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends EntityScrobbleUpdateManyArgs>(args: Prisma.SelectSubset<T, EntityScrobbleUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more EntityScrobbles and returns the data updated in the database.
   * @param {EntityScrobbleUpdateManyAndReturnArgs} args - Arguments to update many EntityScrobbles.
   * @example
   * // Update many EntityScrobbles
   * const entityScrobble = await prisma.entityScrobble.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more EntityScrobbles and only return the `id`
   * const entityScrobbleWithIdOnly = await prisma.entityScrobble.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends EntityScrobbleUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, EntityScrobbleUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$EntityScrobblePayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one EntityScrobble.
   * @param {EntityScrobbleUpsertArgs} args - Arguments to update or create a EntityScrobble.
   * @example
   * // Update or create a EntityScrobble
   * const entityScrobble = await prisma.entityScrobble.upsert({
   *   create: {
   *     // ... data to create a EntityScrobble
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the EntityScrobble we want to update
   *   }
   * })
   */
  upsert<T extends EntityScrobbleUpsertArgs>(args: Prisma.SelectSubset<T, EntityScrobbleUpsertArgs<ExtArgs>>): Prisma.Prisma__EntityScrobbleClient<runtime.Types.Result.GetResult<Prisma.$EntityScrobblePayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of EntityScrobbles.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {EntityScrobbleCountArgs} args - Arguments to filter EntityScrobbles to count.
   * @example
   * // Count the number of EntityScrobbles
   * const count = await prisma.entityScrobble.count({
   *   where: {
   *     // ... the filter for the EntityScrobbles we want to count
   *   }
   * })
  **/
  count<T extends EntityScrobbleCountArgs>(
    args?: Prisma.Subset<T, EntityScrobbleCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], EntityScrobbleCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a EntityScrobble.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {EntityScrobbleAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends EntityScrobbleAggregateArgs>(args: Prisma.Subset<T, EntityScrobbleAggregateArgs>): Prisma.PrismaPromise<GetEntityScrobbleAggregateType<T>>

  /**
   * Group by EntityScrobble.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {EntityScrobbleGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends EntityScrobbleGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: EntityScrobbleGroupByArgs['orderBy'] }
      : { orderBy?: EntityScrobbleGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, EntityScrobbleGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetEntityScrobbleGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the EntityScrobble model
 */
readonly fields: EntityScrobbleFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for EntityScrobble.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__EntityScrobbleClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  lastFmUser<T extends Prisma.LastFmUserDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.LastFmUserDefaultArgs<ExtArgs>>): Prisma.Prisma__LastFmUserClient<runtime.Types.Result.GetResult<Prisma.$LastFmUserPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  entity<T extends Prisma.EntityDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.EntityDefaultArgs<ExtArgs>>): Prisma.Prisma__EntityClient<runtime.Types.Result.GetResult<Prisma.$EntityPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the EntityScrobble model
 */
export interface EntityScrobbleFieldRefs {
  readonly id: Prisma.FieldRef<"EntityScrobble", 'Int'>
  readonly entityId: Prisma.FieldRef<"EntityScrobble", 'Int'>
  readonly fmUsername: Prisma.FieldRef<"EntityScrobble", 'String'>
  readonly playCount: Prisma.FieldRef<"EntityScrobble", 'Int'>
  readonly createdAt: Prisma.FieldRef<"EntityScrobble", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"EntityScrobble", 'DateTime'>
}
    

// Custom InputTypes
/**
 * EntityScrobble findUnique
 */
export type EntityScrobbleFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the EntityScrobble
   */
  select?: Prisma.EntityScrobbleSelect<ExtArgs> | null
  /**
   * Omit specific fields from the EntityScrobble
   */
  omit?: Prisma.EntityScrobbleOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EntityScrobbleInclude<ExtArgs> | null
  /**
   * Filter, which EntityScrobble to fetch.
   */
  where: Prisma.EntityScrobbleWhereUniqueInput
}

/**
 * EntityScrobble findUniqueOrThrow
 */
export type EntityScrobbleFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the EntityScrobble
   */
  select?: Prisma.EntityScrobbleSelect<ExtArgs> | null
  /**
   * Omit specific fields from the EntityScrobble
   */
  omit?: Prisma.EntityScrobbleOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EntityScrobbleInclude<ExtArgs> | null
  /**
   * Filter, which EntityScrobble to fetch.
   */
  where: Prisma.EntityScrobbleWhereUniqueInput
}

/**
 * EntityScrobble findFirst
 */
export type EntityScrobbleFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the EntityScrobble
   */
  select?: Prisma.EntityScrobbleSelect<ExtArgs> | null
  /**
   * Omit specific fields from the EntityScrobble
   */
  omit?: Prisma.EntityScrobbleOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EntityScrobbleInclude<ExtArgs> | null
  /**
   * Filter, which EntityScrobble to fetch.
   */
  where?: Prisma.EntityScrobbleWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of EntityScrobbles to fetch.
   */
  orderBy?: Prisma.EntityScrobbleOrderByWithRelationInput | Prisma.EntityScrobbleOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for EntityScrobbles.
   */
  cursor?: Prisma.EntityScrobbleWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` EntityScrobbles from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` EntityScrobbles.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of EntityScrobbles.
   */
  distinct?: Prisma.EntityScrobbleScalarFieldEnum | Prisma.EntityScrobbleScalarFieldEnum[]
}

/**
 * EntityScrobble findFirstOrThrow
 */
export type EntityScrobbleFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the EntityScrobble
   */
  select?: Prisma.EntityScrobbleSelect<ExtArgs> | null
  /**
   * Omit specific fields from the EntityScrobble
   */
  omit?: Prisma.EntityScrobbleOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EntityScrobbleInclude<ExtArgs> | null
  /**
   * Filter, which EntityScrobble to fetch.
   */
  where?: Prisma.EntityScrobbleWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of EntityScrobbles to fetch.
   */
  orderBy?: Prisma.EntityScrobbleOrderByWithRelationInput | Prisma.EntityScrobbleOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for EntityScrobbles.
   */
  cursor?: Prisma.EntityScrobbleWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` EntityScrobbles from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` EntityScrobbles.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of EntityScrobbles.
   */
  distinct?: Prisma.EntityScrobbleScalarFieldEnum | Prisma.EntityScrobbleScalarFieldEnum[]
}

/**
 * EntityScrobble findMany
 */
export type EntityScrobbleFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the EntityScrobble
   */
  select?: Prisma.EntityScrobbleSelect<ExtArgs> | null
  /**
   * Omit specific fields from the EntityScrobble
   */
  omit?: Prisma.EntityScrobbleOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EntityScrobbleInclude<ExtArgs> | null
  /**
   * Filter, which EntityScrobbles to fetch.
   */
  where?: Prisma.EntityScrobbleWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of EntityScrobbles to fetch.
   */
  orderBy?: Prisma.EntityScrobbleOrderByWithRelationInput | Prisma.EntityScrobbleOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing EntityScrobbles.
   */
  cursor?: Prisma.EntityScrobbleWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` EntityScrobbles from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` EntityScrobbles.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of EntityScrobbles.
   */
  distinct?: Prisma.EntityScrobbleScalarFieldEnum | Prisma.EntityScrobbleScalarFieldEnum[]
}

/**
 * EntityScrobble create
 */
export type EntityScrobbleCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the EntityScrobble
   */
  select?: Prisma.EntityScrobbleSelect<ExtArgs> | null
  /**
   * Omit specific fields from the EntityScrobble
   */
  omit?: Prisma.EntityScrobbleOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EntityScrobbleInclude<ExtArgs> | null
  /**
   * The data needed to create a EntityScrobble.
   */
  data: Prisma.XOR<Prisma.EntityScrobbleCreateInput, Prisma.EntityScrobbleUncheckedCreateInput>
}

/**
 * EntityScrobble createMany
 */
export type EntityScrobbleCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many EntityScrobbles.
   */
  data: Prisma.EntityScrobbleCreateManyInput | Prisma.EntityScrobbleCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * EntityScrobble createManyAndReturn
 */
export type EntityScrobbleCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the EntityScrobble
   */
  select?: Prisma.EntityScrobbleSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the EntityScrobble
   */
  omit?: Prisma.EntityScrobbleOmit<ExtArgs> | null
  /**
   * The data used to create many EntityScrobbles.
   */
  data: Prisma.EntityScrobbleCreateManyInput | Prisma.EntityScrobbleCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EntityScrobbleIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * EntityScrobble update
 */
export type EntityScrobbleUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the EntityScrobble
   */
  select?: Prisma.EntityScrobbleSelect<ExtArgs> | null
  /**
   * Omit specific fields from the EntityScrobble
   */
  omit?: Prisma.EntityScrobbleOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EntityScrobbleInclude<ExtArgs> | null
  /**
   * The data needed to update a EntityScrobble.
   */
  data: Prisma.XOR<Prisma.EntityScrobbleUpdateInput, Prisma.EntityScrobbleUncheckedUpdateInput>
  /**
   * Choose, which EntityScrobble to update.
   */
  where: Prisma.EntityScrobbleWhereUniqueInput
}

/**
 * EntityScrobble updateMany
 */
export type EntityScrobbleUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update EntityScrobbles.
   */
  data: Prisma.XOR<Prisma.EntityScrobbleUpdateManyMutationInput, Prisma.EntityScrobbleUncheckedUpdateManyInput>
  /**
   * Filter which EntityScrobbles to update
   */
  where?: Prisma.EntityScrobbleWhereInput
  /**
   * Limit how many EntityScrobbles to update.
   */
  limit?: number
}

/**
 * EntityScrobble updateManyAndReturn
 */
export type EntityScrobbleUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the EntityScrobble
   */
  select?: Prisma.EntityScrobbleSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the EntityScrobble
   */
  omit?: Prisma.EntityScrobbleOmit<ExtArgs> | null
  /**
   * The data used to update EntityScrobbles.
   */
  data: Prisma.XOR<Prisma.EntityScrobbleUpdateManyMutationInput, Prisma.EntityScrobbleUncheckedUpdateManyInput>
  /**
   * Filter which EntityScrobbles to update
   */
  where?: Prisma.EntityScrobbleWhereInput
  /**
   * Limit how many EntityScrobbles to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EntityScrobbleIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * EntityScrobble upsert
 */
export type EntityScrobbleUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the EntityScrobble
   */
  select?: Prisma.EntityScrobbleSelect<ExtArgs> | null
  /**
   * Omit specific fields from the EntityScrobble
   */
  omit?: Prisma.EntityScrobbleOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EntityScrobbleInclude<ExtArgs> | null
  /**
   * The filter to search for the EntityScrobble to update in case it exists.
   */
  where: Prisma.EntityScrobbleWhereUniqueInput
  /**
   * In case the EntityScrobble found by the `where` argument doesn't exist, create a new EntityScrobble with this data.
   */
  create: Prisma.XOR<Prisma.EntityScrobbleCreateInput, Prisma.EntityScrobbleUncheckedCreateInput>
  /**
   * In case the EntityScrobble was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.EntityScrobbleUpdateInput, Prisma.EntityScrobbleUncheckedUpdateInput>
}

/**
 * EntityScrobble delete
 */
export type EntityScrobbleDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the EntityScrobble
   */
  select?: Prisma.EntityScrobbleSelect<ExtArgs> | null
  /**
   * Omit specific fields from the EntityScrobble
   */
  omit?: Prisma.EntityScrobbleOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EntityScrobbleInclude<ExtArgs> | null
  /**
   * Filter which EntityScrobble to delete.
   */
  where: Prisma.EntityScrobbleWhereUniqueInput
}

/**
 * EntityScrobble deleteMany
 */
export type EntityScrobbleDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which EntityScrobbles to delete
   */
  where?: Prisma.EntityScrobbleWhereInput
  /**
   * Limit how many EntityScrobbles to delete.
   */
  limit?: number
}

/**
 * EntityScrobble without action
 */
export type EntityScrobbleDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the EntityScrobble
   */
  select?: Prisma.EntityScrobbleSelect<ExtArgs> | null
  /**
   * Omit specific fields from the EntityScrobble
   */
  omit?: Prisma.EntityScrobbleOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EntityScrobbleInclude<ExtArgs> | null
}
