
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `LastFmUser` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model LastFmUser
 * 
 */
export type LastFmUserModel = runtime.Types.Result.DefaultSelection<Prisma.$LastFmUserPayload>

export type AggregateLastFmUser = {
  _count: LastFmUserCountAggregateOutputType | null
  _min: LastFmUserMinAggregateOutputType | null
  _max: LastFmUserMaxAggregateOutputType | null
}

export type LastFmUserMinAggregateOutputType = {
  fmUsername: string | null
  displayName: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type LastFmUserMaxAggregateOutputType = {
  fmUsername: string | null
  displayName: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type LastFmUserCountAggregateOutputType = {
  fmUsername: number
  displayName: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type LastFmUserMinAggregateInputType = {
  fmUsername?: true
  displayName?: true
  createdAt?: true
  updatedAt?: true
}

export type LastFmUserMaxAggregateInputType = {
  fmUsername?: true
  displayName?: true
  createdAt?: true
  updatedAt?: true
}

export type LastFmUserCountAggregateInputType = {
  fmUsername?: true
  displayName?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type LastFmUserAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which LastFmUser to aggregate.
   */
  where?: Prisma.LastFmUserWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of LastFmUsers to fetch.
   */
  orderBy?: Prisma.LastFmUserOrderByWithRelationInput | Prisma.LastFmUserOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.LastFmUserWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` LastFmUsers from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` LastFmUsers.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned LastFmUsers
  **/
  _count?: true | LastFmUserCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: LastFmUserMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: LastFmUserMaxAggregateInputType
}

export type GetLastFmUserAggregateType<T extends LastFmUserAggregateArgs> = {
      [P in keyof T & keyof AggregateLastFmUser]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateLastFmUser[P]>
    : Prisma.GetScalarType<T[P], AggregateLastFmUser[P]>
}




export type LastFmUserGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.LastFmUserWhereInput
  orderBy?: Prisma.LastFmUserOrderByWithAggregationInput | Prisma.LastFmUserOrderByWithAggregationInput[]
  by: Prisma.LastFmUserScalarFieldEnum[] | Prisma.LastFmUserScalarFieldEnum
  having?: Prisma.LastFmUserScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: LastFmUserCountAggregateInputType | true
  _min?: LastFmUserMinAggregateInputType
  _max?: LastFmUserMaxAggregateInputType
}

export type LastFmUserGroupByOutputType = {
  fmUsername: string
  displayName: string | null
  createdAt: Date
  updatedAt: Date
  _count: LastFmUserCountAggregateOutputType | null
  _min: LastFmUserMinAggregateOutputType | null
  _max: LastFmUserMaxAggregateOutputType | null
}

export type GetLastFmUserGroupByPayload<T extends LastFmUserGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<LastFmUserGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof LastFmUserGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], LastFmUserGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], LastFmUserGroupByOutputType[P]>
      }
    >
  >



export type LastFmUserWhereInput = {
  AND?: Prisma.LastFmUserWhereInput | Prisma.LastFmUserWhereInput[]
  OR?: Prisma.LastFmUserWhereInput[]
  NOT?: Prisma.LastFmUserWhereInput | Prisma.LastFmUserWhereInput[]
  fmUsername?: Prisma.StringFilter<"LastFmUser"> | string
  displayName?: Prisma.StringNullableFilter<"LastFmUser"> | string | null
  createdAt?: Prisma.DateTimeFilter<"LastFmUser"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"LastFmUser"> | Date | string
  users?: Prisma.UserListRelationFilter
  entityScrobbles?: Prisma.EntityScrobbleListRelationFilter
}

export type LastFmUserOrderByWithRelationInput = {
  fmUsername?: Prisma.SortOrder
  displayName?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  users?: Prisma.UserOrderByRelationAggregateInput
  entityScrobbles?: Prisma.EntityScrobbleOrderByRelationAggregateInput
}

export type LastFmUserWhereUniqueInput = Prisma.AtLeast<{
  fmUsername?: string
  AND?: Prisma.LastFmUserWhereInput | Prisma.LastFmUserWhereInput[]
  OR?: Prisma.LastFmUserWhereInput[]
  NOT?: Prisma.LastFmUserWhereInput | Prisma.LastFmUserWhereInput[]
  displayName?: Prisma.StringNullableFilter<"LastFmUser"> | string | null
  createdAt?: Prisma.DateTimeFilter<"LastFmUser"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"LastFmUser"> | Date | string
  users?: Prisma.UserListRelationFilter
  entityScrobbles?: Prisma.EntityScrobbleListRelationFilter
}, "fmUsername">

export type LastFmUserOrderByWithAggregationInput = {
  fmUsername?: Prisma.SortOrder
  displayName?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.LastFmUserCountOrderByAggregateInput
  _max?: Prisma.LastFmUserMaxOrderByAggregateInput
  _min?: Prisma.LastFmUserMinOrderByAggregateInput
}

export type LastFmUserScalarWhereWithAggregatesInput = {
  AND?: Prisma.LastFmUserScalarWhereWithAggregatesInput | Prisma.LastFmUserScalarWhereWithAggregatesInput[]
  OR?: Prisma.LastFmUserScalarWhereWithAggregatesInput[]
  NOT?: Prisma.LastFmUserScalarWhereWithAggregatesInput | Prisma.LastFmUserScalarWhereWithAggregatesInput[]
  fmUsername?: Prisma.StringWithAggregatesFilter<"LastFmUser"> | string
  displayName?: Prisma.StringNullableWithAggregatesFilter<"LastFmUser"> | string | null
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"LastFmUser"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"LastFmUser"> | Date | string
}

export type LastFmUserCreateInput = {
  fmUsername: string
  displayName?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  users?: Prisma.UserCreateNestedManyWithoutLastFmUserInput
  entityScrobbles?: Prisma.EntityScrobbleCreateNestedManyWithoutLastFmUserInput
}

export type LastFmUserUncheckedCreateInput = {
  fmUsername: string
  displayName?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  users?: Prisma.UserUncheckedCreateNestedManyWithoutLastFmUserInput
  entityScrobbles?: Prisma.EntityScrobbleUncheckedCreateNestedManyWithoutLastFmUserInput
}

export type LastFmUserUpdateInput = {
  fmUsername?: Prisma.StringFieldUpdateOperationsInput | string
  displayName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  users?: Prisma.UserUpdateManyWithoutLastFmUserNestedInput
  entityScrobbles?: Prisma.EntityScrobbleUpdateManyWithoutLastFmUserNestedInput
}

export type LastFmUserUncheckedUpdateInput = {
  fmUsername?: Prisma.StringFieldUpdateOperationsInput | string
  displayName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  users?: Prisma.UserUncheckedUpdateManyWithoutLastFmUserNestedInput
  entityScrobbles?: Prisma.EntityScrobbleUncheckedUpdateManyWithoutLastFmUserNestedInput
}

export type LastFmUserCreateManyInput = {
  fmUsername: string
  displayName?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type LastFmUserUpdateManyMutationInput = {
  fmUsername?: Prisma.StringFieldUpdateOperationsInput | string
  displayName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type LastFmUserUncheckedUpdateManyInput = {
  fmUsername?: Prisma.StringFieldUpdateOperationsInput | string
  displayName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type LastFmUserScalarRelationFilter = {
  is?: Prisma.LastFmUserWhereInput
  isNot?: Prisma.LastFmUserWhereInput
}

export type LastFmUserCountOrderByAggregateInput = {
  fmUsername?: Prisma.SortOrder
  displayName?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type LastFmUserMaxOrderByAggregateInput = {
  fmUsername?: Prisma.SortOrder
  displayName?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type LastFmUserMinOrderByAggregateInput = {
  fmUsername?: Prisma.SortOrder
  displayName?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type LastFmUserCreateNestedOneWithoutUsersInput = {
  create?: Prisma.XOR<Prisma.LastFmUserCreateWithoutUsersInput, Prisma.LastFmUserUncheckedCreateWithoutUsersInput>
  connectOrCreate?: Prisma.LastFmUserCreateOrConnectWithoutUsersInput
  connect?: Prisma.LastFmUserWhereUniqueInput
}

export type LastFmUserUpdateOneRequiredWithoutUsersNestedInput = {
  create?: Prisma.XOR<Prisma.LastFmUserCreateWithoutUsersInput, Prisma.LastFmUserUncheckedCreateWithoutUsersInput>
  connectOrCreate?: Prisma.LastFmUserCreateOrConnectWithoutUsersInput
  upsert?: Prisma.LastFmUserUpsertWithoutUsersInput
  connect?: Prisma.LastFmUserWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.LastFmUserUpdateToOneWithWhereWithoutUsersInput, Prisma.LastFmUserUpdateWithoutUsersInput>, Prisma.LastFmUserUncheckedUpdateWithoutUsersInput>
}

export type LastFmUserCreateNestedOneWithoutEntityScrobblesInput = {
  create?: Prisma.XOR<Prisma.LastFmUserCreateWithoutEntityScrobblesInput, Prisma.LastFmUserUncheckedCreateWithoutEntityScrobblesInput>
  connectOrCreate?: Prisma.LastFmUserCreateOrConnectWithoutEntityScrobblesInput
  connect?: Prisma.LastFmUserWhereUniqueInput
}

export type LastFmUserUpdateOneRequiredWithoutEntityScrobblesNestedInput = {
  create?: Prisma.XOR<Prisma.LastFmUserCreateWithoutEntityScrobblesInput, Prisma.LastFmUserUncheckedCreateWithoutEntityScrobblesInput>
  connectOrCreate?: Prisma.LastFmUserCreateOrConnectWithoutEntityScrobblesInput
  upsert?: Prisma.LastFmUserUpsertWithoutEntityScrobblesInput
  connect?: Prisma.LastFmUserWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.LastFmUserUpdateToOneWithWhereWithoutEntityScrobblesInput, Prisma.LastFmUserUpdateWithoutEntityScrobblesInput>, Prisma.LastFmUserUncheckedUpdateWithoutEntityScrobblesInput>
}

export type LastFmUserCreateWithoutUsersInput = {
  fmUsername: string
  displayName?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  entityScrobbles?: Prisma.EntityScrobbleCreateNestedManyWithoutLastFmUserInput
}

export type LastFmUserUncheckedCreateWithoutUsersInput = {
  fmUsername: string
  displayName?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  entityScrobbles?: Prisma.EntityScrobbleUncheckedCreateNestedManyWithoutLastFmUserInput
}

export type LastFmUserCreateOrConnectWithoutUsersInput = {
  where: Prisma.LastFmUserWhereUniqueInput
  create: Prisma.XOR<Prisma.LastFmUserCreateWithoutUsersInput, Prisma.LastFmUserUncheckedCreateWithoutUsersInput>
}

export type LastFmUserUpsertWithoutUsersInput = {
  update: Prisma.XOR<Prisma.LastFmUserUpdateWithoutUsersInput, Prisma.LastFmUserUncheckedUpdateWithoutUsersInput>
  create: Prisma.XOR<Prisma.LastFmUserCreateWithoutUsersInput, Prisma.LastFmUserUncheckedCreateWithoutUsersInput>
  where?: Prisma.LastFmUserWhereInput
}

export type LastFmUserUpdateToOneWithWhereWithoutUsersInput = {
  where?: Prisma.LastFmUserWhereInput
  data: Prisma.XOR<Prisma.LastFmUserUpdateWithoutUsersInput, Prisma.LastFmUserUncheckedUpdateWithoutUsersInput>
}

export type LastFmUserUpdateWithoutUsersInput = {
  fmUsername?: Prisma.StringFieldUpdateOperationsInput | string
  displayName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  entityScrobbles?: Prisma.EntityScrobbleUpdateManyWithoutLastFmUserNestedInput
}

export type LastFmUserUncheckedUpdateWithoutUsersInput = {
  fmUsername?: Prisma.StringFieldUpdateOperationsInput | string
  displayName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  entityScrobbles?: Prisma.EntityScrobbleUncheckedUpdateManyWithoutLastFmUserNestedInput
}

export type LastFmUserCreateWithoutEntityScrobblesInput = {
  fmUsername: string
  displayName?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  users?: Prisma.UserCreateNestedManyWithoutLastFmUserInput
}

export type LastFmUserUncheckedCreateWithoutEntityScrobblesInput = {
  fmUsername: string
  displayName?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  users?: Prisma.UserUncheckedCreateNestedManyWithoutLastFmUserInput
}

export type LastFmUserCreateOrConnectWithoutEntityScrobblesInput = {
  where: Prisma.LastFmUserWhereUniqueInput
  create: Prisma.XOR<Prisma.LastFmUserCreateWithoutEntityScrobblesInput, Prisma.LastFmUserUncheckedCreateWithoutEntityScrobblesInput>
}

export type LastFmUserUpsertWithoutEntityScrobblesInput = {
  update: Prisma.XOR<Prisma.LastFmUserUpdateWithoutEntityScrobblesInput, Prisma.LastFmUserUncheckedUpdateWithoutEntityScrobblesInput>
  create: Prisma.XOR<Prisma.LastFmUserCreateWithoutEntityScrobblesInput, Prisma.LastFmUserUncheckedCreateWithoutEntityScrobblesInput>
  where?: Prisma.LastFmUserWhereInput
}

export type LastFmUserUpdateToOneWithWhereWithoutEntityScrobblesInput = {
  where?: Prisma.LastFmUserWhereInput
  data: Prisma.XOR<Prisma.LastFmUserUpdateWithoutEntityScrobblesInput, Prisma.LastFmUserUncheckedUpdateWithoutEntityScrobblesInput>
}

export type LastFmUserUpdateWithoutEntityScrobblesInput = {
  fmUsername?: Prisma.StringFieldUpdateOperationsInput | string
  displayName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  users?: Prisma.UserUpdateManyWithoutLastFmUserNestedInput
}

export type LastFmUserUncheckedUpdateWithoutEntityScrobblesInput = {
  fmUsername?: Prisma.StringFieldUpdateOperationsInput | string
  displayName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  users?: Prisma.UserUncheckedUpdateManyWithoutLastFmUserNestedInput
}


/**
 * Count Type LastFmUserCountOutputType
 */

export type LastFmUserCountOutputType = {
  users: number
  entityScrobbles: number
}

export type LastFmUserCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  users?: boolean | LastFmUserCountOutputTypeCountUsersArgs
  entityScrobbles?: boolean | LastFmUserCountOutputTypeCountEntityScrobblesArgs
}

/**
 * LastFmUserCountOutputType without action
 */
export type LastFmUserCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the LastFmUserCountOutputType
   */
  select?: Prisma.LastFmUserCountOutputTypeSelect<ExtArgs> | null
}

/**
 * LastFmUserCountOutputType without action
 */
export type LastFmUserCountOutputTypeCountUsersArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.UserWhereInput
}

/**
 * LastFmUserCountOutputType without action
 */
export type LastFmUserCountOutputTypeCountEntityScrobblesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.EntityScrobbleWhereInput
}


export type LastFmUserSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  fmUsername?: boolean
  displayName?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  users?: boolean | Prisma.LastFmUser$usersArgs<ExtArgs>
  entityScrobbles?: boolean | Prisma.LastFmUser$entityScrobblesArgs<ExtArgs>
  _count?: boolean | Prisma.LastFmUserCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["lastFmUser"]>

export type LastFmUserSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  fmUsername?: boolean
  displayName?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["lastFmUser"]>

export type LastFmUserSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  fmUsername?: boolean
  displayName?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["lastFmUser"]>

export type LastFmUserSelectScalar = {
  fmUsername?: boolean
  displayName?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type LastFmUserOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"fmUsername" | "displayName" | "createdAt" | "updatedAt", ExtArgs["result"]["lastFmUser"]>
export type LastFmUserInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  users?: boolean | Prisma.LastFmUser$usersArgs<ExtArgs>
  entityScrobbles?: boolean | Prisma.LastFmUser$entityScrobblesArgs<ExtArgs>
  _count?: boolean | Prisma.LastFmUserCountOutputTypeDefaultArgs<ExtArgs>
}
export type LastFmUserIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}
export type LastFmUserIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}

export type $LastFmUserPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "LastFmUser"
  objects: {
    users: Prisma.$UserPayload<ExtArgs>[]
    entityScrobbles: Prisma.$EntityScrobblePayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    fmUsername: string
    displayName: string | null
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["lastFmUser"]>
  composites: {}
}

export type LastFmUserGetPayload<S extends boolean | null | undefined | LastFmUserDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$LastFmUserPayload, S>

export type LastFmUserCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<LastFmUserFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: LastFmUserCountAggregateInputType | true
  }

export interface LastFmUserDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['LastFmUser'], meta: { name: 'LastFmUser' } }
  /**
   * Find zero or one LastFmUser that matches the filter.
   * @param {LastFmUserFindUniqueArgs} args - Arguments to find a LastFmUser
   * @example
   * // Get one LastFmUser
   * const lastFmUser = await prisma.lastFmUser.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends LastFmUserFindUniqueArgs>(args: Prisma.SelectSubset<T, LastFmUserFindUniqueArgs<ExtArgs>>): Prisma.Prisma__LastFmUserClient<runtime.Types.Result.GetResult<Prisma.$LastFmUserPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one LastFmUser that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {LastFmUserFindUniqueOrThrowArgs} args - Arguments to find a LastFmUser
   * @example
   * // Get one LastFmUser
   * const lastFmUser = await prisma.lastFmUser.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends LastFmUserFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, LastFmUserFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__LastFmUserClient<runtime.Types.Result.GetResult<Prisma.$LastFmUserPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first LastFmUser that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {LastFmUserFindFirstArgs} args - Arguments to find a LastFmUser
   * @example
   * // Get one LastFmUser
   * const lastFmUser = await prisma.lastFmUser.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends LastFmUserFindFirstArgs>(args?: Prisma.SelectSubset<T, LastFmUserFindFirstArgs<ExtArgs>>): Prisma.Prisma__LastFmUserClient<runtime.Types.Result.GetResult<Prisma.$LastFmUserPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first LastFmUser that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {LastFmUserFindFirstOrThrowArgs} args - Arguments to find a LastFmUser
   * @example
   * // Get one LastFmUser
   * const lastFmUser = await prisma.lastFmUser.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends LastFmUserFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, LastFmUserFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__LastFmUserClient<runtime.Types.Result.GetResult<Prisma.$LastFmUserPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more LastFmUsers that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {LastFmUserFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all LastFmUsers
   * const lastFmUsers = await prisma.lastFmUser.findMany()
   * 
   * // Get first 10 LastFmUsers
   * const lastFmUsers = await prisma.lastFmUser.findMany({ take: 10 })
   * 
   * // Only select the `fmUsername`
   * const lastFmUserWithFmUsernameOnly = await prisma.lastFmUser.findMany({ select: { fmUsername: true } })
   * 
   */
  findMany<T extends LastFmUserFindManyArgs>(args?: Prisma.SelectSubset<T, LastFmUserFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$LastFmUserPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a LastFmUser.
   * @param {LastFmUserCreateArgs} args - Arguments to create a LastFmUser.
   * @example
   * // Create one LastFmUser
   * const LastFmUser = await prisma.lastFmUser.create({
   *   data: {
   *     // ... data to create a LastFmUser
   *   }
   * })
   * 
   */
  create<T extends LastFmUserCreateArgs>(args: Prisma.SelectSubset<T, LastFmUserCreateArgs<ExtArgs>>): Prisma.Prisma__LastFmUserClient<runtime.Types.Result.GetResult<Prisma.$LastFmUserPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many LastFmUsers.
   * @param {LastFmUserCreateManyArgs} args - Arguments to create many LastFmUsers.
   * @example
   * // Create many LastFmUsers
   * const lastFmUser = await prisma.lastFmUser.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends LastFmUserCreateManyArgs>(args?: Prisma.SelectSubset<T, LastFmUserCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many LastFmUsers and returns the data saved in the database.
   * @param {LastFmUserCreateManyAndReturnArgs} args - Arguments to create many LastFmUsers.
   * @example
   * // Create many LastFmUsers
   * const lastFmUser = await prisma.lastFmUser.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many LastFmUsers and only return the `fmUsername`
   * const lastFmUserWithFmUsernameOnly = await prisma.lastFmUser.createManyAndReturn({
   *   select: { fmUsername: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends LastFmUserCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, LastFmUserCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$LastFmUserPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a LastFmUser.
   * @param {LastFmUserDeleteArgs} args - Arguments to delete one LastFmUser.
   * @example
   * // Delete one LastFmUser
   * const LastFmUser = await prisma.lastFmUser.delete({
   *   where: {
   *     // ... filter to delete one LastFmUser
   *   }
   * })
   * 
   */
  delete<T extends LastFmUserDeleteArgs>(args: Prisma.SelectSubset<T, LastFmUserDeleteArgs<ExtArgs>>): Prisma.Prisma__LastFmUserClient<runtime.Types.Result.GetResult<Prisma.$LastFmUserPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one LastFmUser.
   * @param {LastFmUserUpdateArgs} args - Arguments to update one LastFmUser.
   * @example
   * // Update one LastFmUser
   * const lastFmUser = await prisma.lastFmUser.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends LastFmUserUpdateArgs>(args: Prisma.SelectSubset<T, LastFmUserUpdateArgs<ExtArgs>>): Prisma.Prisma__LastFmUserClient<runtime.Types.Result.GetResult<Prisma.$LastFmUserPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more LastFmUsers.
   * @param {LastFmUserDeleteManyArgs} args - Arguments to filter LastFmUsers to delete.
   * @example
   * // Delete a few LastFmUsers
   * const { count } = await prisma.lastFmUser.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends LastFmUserDeleteManyArgs>(args?: Prisma.SelectSubset<T, LastFmUserDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more LastFmUsers.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {LastFmUserUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many LastFmUsers
   * const lastFmUser = await prisma.lastFmUser.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends LastFmUserUpdateManyArgs>(args: Prisma.SelectSubset<T, LastFmUserUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more LastFmUsers and returns the data updated in the database.
   * @param {LastFmUserUpdateManyAndReturnArgs} args - Arguments to update many LastFmUsers.
   * @example
   * // Update many LastFmUsers
   * const lastFmUser = await prisma.lastFmUser.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more LastFmUsers and only return the `fmUsername`
   * const lastFmUserWithFmUsernameOnly = await prisma.lastFmUser.updateManyAndReturn({
   *   select: { fmUsername: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends LastFmUserUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, LastFmUserUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$LastFmUserPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one LastFmUser.
   * @param {LastFmUserUpsertArgs} args - Arguments to update or create a LastFmUser.
   * @example
   * // Update or create a LastFmUser
   * const lastFmUser = await prisma.lastFmUser.upsert({
   *   create: {
   *     // ... data to create a LastFmUser
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the LastFmUser we want to update
   *   }
   * })
   */
  upsert<T extends LastFmUserUpsertArgs>(args: Prisma.SelectSubset<T, LastFmUserUpsertArgs<ExtArgs>>): Prisma.Prisma__LastFmUserClient<runtime.Types.Result.GetResult<Prisma.$LastFmUserPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of LastFmUsers.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {LastFmUserCountArgs} args - Arguments to filter LastFmUsers to count.
   * @example
   * // Count the number of LastFmUsers
   * const count = await prisma.lastFmUser.count({
   *   where: {
   *     // ... the filter for the LastFmUsers we want to count
   *   }
   * })
  **/
  count<T extends LastFmUserCountArgs>(
    args?: Prisma.Subset<T, LastFmUserCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], LastFmUserCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a LastFmUser.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {LastFmUserAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends LastFmUserAggregateArgs>(args: Prisma.Subset<T, LastFmUserAggregateArgs>): Prisma.PrismaPromise<GetLastFmUserAggregateType<T>>

  /**
   * Group by LastFmUser.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {LastFmUserGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends LastFmUserGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: LastFmUserGroupByArgs['orderBy'] }
      : { orderBy?: LastFmUserGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, LastFmUserGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetLastFmUserGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the LastFmUser model
 */
readonly fields: LastFmUserFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for LastFmUser.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__LastFmUserClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  users<T extends Prisma.LastFmUser$usersArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.LastFmUser$usersArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  entityScrobbles<T extends Prisma.LastFmUser$entityScrobblesArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.LastFmUser$entityScrobblesArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$EntityScrobblePayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the LastFmUser model
 */
export interface LastFmUserFieldRefs {
  readonly fmUsername: Prisma.FieldRef<"LastFmUser", 'String'>
  readonly displayName: Prisma.FieldRef<"LastFmUser", 'String'>
  readonly createdAt: Prisma.FieldRef<"LastFmUser", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"LastFmUser", 'DateTime'>
}
    

// Custom InputTypes
/**
 * LastFmUser findUnique
 */
export type LastFmUserFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the LastFmUser
   */
  select?: Prisma.LastFmUserSelect<ExtArgs> | null
  /**
   * Omit specific fields from the LastFmUser
   */
  omit?: Prisma.LastFmUserOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LastFmUserInclude<ExtArgs> | null
  /**
   * Filter, which LastFmUser to fetch.
   */
  where: Prisma.LastFmUserWhereUniqueInput
}

/**
 * LastFmUser findUniqueOrThrow
 */
export type LastFmUserFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the LastFmUser
   */
  select?: Prisma.LastFmUserSelect<ExtArgs> | null
  /**
   * Omit specific fields from the LastFmUser
   */
  omit?: Prisma.LastFmUserOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LastFmUserInclude<ExtArgs> | null
  /**
   * Filter, which LastFmUser to fetch.
   */
  where: Prisma.LastFmUserWhereUniqueInput
}

/**
 * LastFmUser findFirst
 */
export type LastFmUserFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the LastFmUser
   */
  select?: Prisma.LastFmUserSelect<ExtArgs> | null
  /**
   * Omit specific fields from the LastFmUser
   */
  omit?: Prisma.LastFmUserOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LastFmUserInclude<ExtArgs> | null
  /**
   * Filter, which LastFmUser to fetch.
   */
  where?: Prisma.LastFmUserWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of LastFmUsers to fetch.
   */
  orderBy?: Prisma.LastFmUserOrderByWithRelationInput | Prisma.LastFmUserOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for LastFmUsers.
   */
  cursor?: Prisma.LastFmUserWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` LastFmUsers from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` LastFmUsers.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of LastFmUsers.
   */
  distinct?: Prisma.LastFmUserScalarFieldEnum | Prisma.LastFmUserScalarFieldEnum[]
}

/**
 * LastFmUser findFirstOrThrow
 */
export type LastFmUserFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the LastFmUser
   */
  select?: Prisma.LastFmUserSelect<ExtArgs> | null
  /**
   * Omit specific fields from the LastFmUser
   */
  omit?: Prisma.LastFmUserOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LastFmUserInclude<ExtArgs> | null
  /**
   * Filter, which LastFmUser to fetch.
   */
  where?: Prisma.LastFmUserWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of LastFmUsers to fetch.
   */
  orderBy?: Prisma.LastFmUserOrderByWithRelationInput | Prisma.LastFmUserOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for LastFmUsers.
   */
  cursor?: Prisma.LastFmUserWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` LastFmUsers from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` LastFmUsers.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of LastFmUsers.
   */
  distinct?: Prisma.LastFmUserScalarFieldEnum | Prisma.LastFmUserScalarFieldEnum[]
}

/**
 * LastFmUser findMany
 */
export type LastFmUserFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the LastFmUser
   */
  select?: Prisma.LastFmUserSelect<ExtArgs> | null
  /**
   * Omit specific fields from the LastFmUser
   */
  omit?: Prisma.LastFmUserOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LastFmUserInclude<ExtArgs> | null
  /**
   * Filter, which LastFmUsers to fetch.
   */
  where?: Prisma.LastFmUserWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of LastFmUsers to fetch.
   */
  orderBy?: Prisma.LastFmUserOrderByWithRelationInput | Prisma.LastFmUserOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing LastFmUsers.
   */
  cursor?: Prisma.LastFmUserWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` LastFmUsers from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` LastFmUsers.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of LastFmUsers.
   */
  distinct?: Prisma.LastFmUserScalarFieldEnum | Prisma.LastFmUserScalarFieldEnum[]
}

/**
 * LastFmUser create
 */
export type LastFmUserCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the LastFmUser
   */
  select?: Prisma.LastFmUserSelect<ExtArgs> | null
  /**
   * Omit specific fields from the LastFmUser
   */
  omit?: Prisma.LastFmUserOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LastFmUserInclude<ExtArgs> | null
  /**
   * The data needed to create a LastFmUser.
   */
  data: Prisma.XOR<Prisma.LastFmUserCreateInput, Prisma.LastFmUserUncheckedCreateInput>
}

/**
 * LastFmUser createMany
 */
export type LastFmUserCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many LastFmUsers.
   */
  data: Prisma.LastFmUserCreateManyInput | Prisma.LastFmUserCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * LastFmUser createManyAndReturn
 */
export type LastFmUserCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the LastFmUser
   */
  select?: Prisma.LastFmUserSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the LastFmUser
   */
  omit?: Prisma.LastFmUserOmit<ExtArgs> | null
  /**
   * The data used to create many LastFmUsers.
   */
  data: Prisma.LastFmUserCreateManyInput | Prisma.LastFmUserCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * LastFmUser update
 */
export type LastFmUserUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the LastFmUser
   */
  select?: Prisma.LastFmUserSelect<ExtArgs> | null
  /**
   * Omit specific fields from the LastFmUser
   */
  omit?: Prisma.LastFmUserOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LastFmUserInclude<ExtArgs> | null
  /**
   * The data needed to update a LastFmUser.
   */
  data: Prisma.XOR<Prisma.LastFmUserUpdateInput, Prisma.LastFmUserUncheckedUpdateInput>
  /**
   * Choose, which LastFmUser to update.
   */
  where: Prisma.LastFmUserWhereUniqueInput
}

/**
 * LastFmUser updateMany
 */
export type LastFmUserUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update LastFmUsers.
   */
  data: Prisma.XOR<Prisma.LastFmUserUpdateManyMutationInput, Prisma.LastFmUserUncheckedUpdateManyInput>
  /**
   * Filter which LastFmUsers to update
   */
  where?: Prisma.LastFmUserWhereInput
  /**
   * Limit how many LastFmUsers to update.
   */
  limit?: number
}

/**
 * LastFmUser updateManyAndReturn
 */
export type LastFmUserUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the LastFmUser
   */
  select?: Prisma.LastFmUserSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the LastFmUser
   */
  omit?: Prisma.LastFmUserOmit<ExtArgs> | null
  /**
   * The data used to update LastFmUsers.
   */
  data: Prisma.XOR<Prisma.LastFmUserUpdateManyMutationInput, Prisma.LastFmUserUncheckedUpdateManyInput>
  /**
   * Filter which LastFmUsers to update
   */
  where?: Prisma.LastFmUserWhereInput
  /**
   * Limit how many LastFmUsers to update.
   */
  limit?: number
}

/**
 * LastFmUser upsert
 */
export type LastFmUserUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the LastFmUser
   */
  select?: Prisma.LastFmUserSelect<ExtArgs> | null
  /**
   * Omit specific fields from the LastFmUser
   */
  omit?: Prisma.LastFmUserOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LastFmUserInclude<ExtArgs> | null
  /**
   * The filter to search for the LastFmUser to update in case it exists.
   */
  where: Prisma.LastFmUserWhereUniqueInput
  /**
   * In case the LastFmUser found by the `where` argument doesn't exist, create a new LastFmUser with this data.
   */
  create: Prisma.XOR<Prisma.LastFmUserCreateInput, Prisma.LastFmUserUncheckedCreateInput>
  /**
   * In case the LastFmUser was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.LastFmUserUpdateInput, Prisma.LastFmUserUncheckedUpdateInput>
}

/**
 * LastFmUser delete
 */
export type LastFmUserDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the LastFmUser
   */
  select?: Prisma.LastFmUserSelect<ExtArgs> | null
  /**
   * Omit specific fields from the LastFmUser
   */
  omit?: Prisma.LastFmUserOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LastFmUserInclude<ExtArgs> | null
  /**
   * Filter which LastFmUser to delete.
   */
  where: Prisma.LastFmUserWhereUniqueInput
}

/**
 * LastFmUser deleteMany
 */
export type LastFmUserDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which LastFmUsers to delete
   */
  where?: Prisma.LastFmUserWhereInput
  /**
   * Limit how many LastFmUsers to delete.
   */
  limit?: number
}

/**
 * LastFmUser.users
 */
export type LastFmUser$usersArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the User
   */
  select?: Prisma.UserSelect<ExtArgs> | null
  /**
   * Omit specific fields from the User
   */
  omit?: Prisma.UserOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserInclude<ExtArgs> | null
  where?: Prisma.UserWhereInput
  orderBy?: Prisma.UserOrderByWithRelationInput | Prisma.UserOrderByWithRelationInput[]
  cursor?: Prisma.UserWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.UserScalarFieldEnum | Prisma.UserScalarFieldEnum[]
}

/**
 * LastFmUser.entityScrobbles
 */
export type LastFmUser$entityScrobblesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the EntityScrobble
   */
  select?: Prisma.EntityScrobbleSelect<ExtArgs> | null
  /**
   * Omit specific fields from the EntityScrobble
   */
  omit?: Prisma.EntityScrobbleOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EntityScrobbleInclude<ExtArgs> | null
  where?: Prisma.EntityScrobbleWhereInput
  orderBy?: Prisma.EntityScrobbleOrderByWithRelationInput | Prisma.EntityScrobbleOrderByWithRelationInput[]
  cursor?: Prisma.EntityScrobbleWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.EntityScrobbleScalarFieldEnum | Prisma.EntityScrobbleScalarFieldEnum[]
}

/**
 * LastFmUser without action
 */
export type LastFmUserDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the LastFmUser
   */
  select?: Prisma.LastFmUserSelect<ExtArgs> | null
  /**
   * Omit specific fields from the LastFmUser
   */
  omit?: Prisma.LastFmUserOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LastFmUserInclude<ExtArgs> | null
}
