name: Build and deploy

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: read
  packages: write

jobs:
  deploy:
    uses: musicorum-app/gh-actions/.github/workflows/dokploy-deploy.yml@main
    secrets: inherit