name: Deploy for production

on:
  workflow_run: 
    workflows: [Build and deploy]
    types:
      - completed
  workflow_dispatch:

jobs:
  deploy:
    name: "Production deploy"
    runs-on: ubuntu-latest
    environment: production
    
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Promote build image to production
        run: |
          docker buildx imagetools create \
            --tag ghcr.io/${{ github.repository }}:production \
            ghcr.io/${{ github.repository }}:latest

      - name: TODO
        run: echo "not implemented yet!" && exit 1
